INSERT INTO permission_category (category_id, category, description, level, enabled, active, folders, lookups, viewpoints, categories, scheduled_events, object_events, reports, webdav, logos, constant, action_plans, custom_list_views) VALUES (50, 'Farmacosorveglianza', NULL, 800, true, true, true, true, false, false, false, false, true, true, false, 13144167, true, false);
INSERT INTO permission (permission_id, category_id, permission, permission_view, permission_add, permission_edit, permission_delete, description, level, enabled, active, viewpoints) VALUES (362, 50, 'farmacosorveglianza-farmacosorveglianza-history', true, true, true, true, 'Storia Farmacosorveglianza', 151, true, true, false);
INSERT INTO permission (permission_id, category_id, permission, permission_view, permission_add, permission_edit, permission_delete, description, level, enabled, active, viewpoints) VALUES (363, 50, 'farmacosorveglianza', true, true, true, true, 'Accesso Farmacosorveglianza', 15, true, true, false);
INSERT INTO permission (permission_id, category_id, permission, permission_view, permission_add, permission_edit, permission_delete, description, level, enabled, active, viewpoints) VALUES (364, 50, 'farmacosorveglianza-farmacosorveglianza', true, true, true, true, 'Farmacosorveglianza', 15, true, true, false);




CREATE TABLE veterinari2
(
  id_veterinario integer NOT NULL DEFAULT nextval(('veterinario_id_seq'::text)::regclass),
  nome character varying(50),
  cognome character varying(50),
  codice_fiscale character varying(16),
  id_tipologia integer,
  indirizzo character varying(80),
  "citta'" character varying(80),
  provincia character varying(80),
  stato character varying(80),
  postalcode character varying(12),
  note1 text,
  note2 text,
  entered timestamp(3) without time zone NOT NULL DEFAULT now(),
  enteredby integer NOT NULL,
  modified timestamp(3) without time zone NOT NULL DEFAULT now(),
  modifiedby integer NOT NULL,
  trashed_date timestamp(3) without time zone,
  citta character varying(80),
  site_id integer
)
WITH (OIDS=FALSE);
ALTER TABLE veterinari2 OWNER TO postgres;



CREATE TABLE lookup_tipologia_veterinario
(
  code serial NOT NULL,
  description character varying(300) NOT NULL,
  short_description character varying(300),
  default_item boolean DEFAULT false,
  "level" integer DEFAULT 0,
  enabled boolean DEFAULT true,
  CONSTRAINT lookup_tipologia_veterinario_pkey PRIMARY KEY (code)
)
WITH (OIDS=FALSE);
ALTER TABLE lookup_tipologia_veterinario OWNER TO postgres;


INSERT INTO lookup_tipologia_veterinario (code, description, short_description, default_item, level, enabled) VALUES (1, 'Privato', 'Privato', false, 1, true);
INSERT INTO lookup_tipologia_veterinario (code, description, short_description, default_item, level, enabled) VALUES (2, 'ASL', 'ASL', false, 2, true);


CREATE SEQUENCE farmaci_id_farmaco_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE farmaci_id_farmaco_seq OWNER TO postgres;

CREATE SEQUENCE farmacia_id_seq
  INCREMENT 1
  MINVALUE 0
  MAXVALUE 9223372036854775807
  START 13
  CACHE 1;
ALTER TABLE farmacia_id_seq OWNER TO postgres;



CREATE SEQUENCE farmacie_id_farmacia_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 33
  CACHE 1;
ALTER TABLE farmacie_id_farmacia_seq OWNER TO postgres;


CREATE SEQUENCE farmaco_id_seq
  INCREMENT 1
  MINVALUE 0
  MAXVALUE 9223372036854775807
  START 14
  CACHE 1;
ALTER TABLE farmaco_id_seq OWNER TO postgres;

CREATE TABLE farmaci2
(
  id_farmaco integer NOT NULL DEFAULT nextval(('farmaco_id_seq'::text)::regclass),
  nome_commerciale character varying(50),
  principio_attivo character varying(50),
  tipo_somministrazione character varying(50),
  quantita integer,
  note1 text,
  note2 text,
  entered timestamp(3) without time zone NOT NULL DEFAULT now(),
  enteredby integer NOT NULL,
  modified timestamp(3) without time zone NOT NULL DEFAULT now(),
  modifiedby integer NOT NULL,
  trashed_date timestamp(3) without time zone,
  prezzo double precision DEFAULT 0,
  id_tiposomministrazione integer,
  id_confezione integer,
  ditta character varying(80),
  gruppo_merceologico character varying(80),
  id_prescrizione integer
)
WITH (OIDS=FALSE);
ALTER TABLE farmaci2 OWNER TO postgres;


CREATE TABLE farmacie
(
  id_farmacia integer NOT NULL DEFAULT nextval(('farmacia_id_seq'::text)::regclass),
  ragione_sociale character varying(50),
  site_id integer,
  indirizzo character varying(80),
  "citta'" character varying(80),
  provincia character varying(80),
  stato character varying(80),
  postalcode character varying(12),
  latitude double precision DEFAULT 0,
  longitude double precision DEFAULT 0,
  note1 text,
  note2 text,
  entered timestamp(3) without time zone NOT NULL DEFAULT now(),
  enteredby integer NOT NULL,
  modified timestamp(3) without time zone NOT NULL DEFAULT now(),
  modifiedby integer NOT NULL,
  trashed_date timestamp(3) without time zone,
  citta character varying(80),
  id_prescrizione integer
)
WITH (OIDS=FALSE);
ALTER TABLE farmacie OWNER TO postgres;


CREATE TABLE prescrizioni2
(
  id_prescrizione integer NOT NULL DEFAULT nextval(('prescrizione_id_seq'::text)::regclass),
  site_id integer,
  data_prescrizione timestamp(3) without time zone,
  data_dispensazione timestamp(3) without time zone,
  id_farmacia integer,
  id_farmaco1 integer,
  quantita_farmaco1 integer,
  id_farmaco2 integer,
  quantita_farmaco2 integer,
  id_veterinario integer,
  org_id integer,
  note1 text,
  note2 text,
  entered timestamp(3) without time zone NOT NULL DEFAULT now(),
  enteredby integer NOT NULL,
  modified timestamp(3) without time zone NOT NULL DEFAULT now(),
  modifiedby integer NOT NULL,
  trashed_date timestamp(3) without time zone
)
WITH (OIDS=FALSE);
ALTER TABLE prescrizioni2 OWNER TO postgres;


INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Capozza Claudia                            ', 1 ,'Via S.Rocco                                               ', '29/04/1993', 'AV ', '        ', '15/C.112/g ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Avellino                              ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Ce.Di.Far.Me.Coop arl                      ', 1 ,'Via Fontana Angelica,1                                    ', '09/08/1993', 'AV ', '        ', '15/C.104/g ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Ariano Irpino                         ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'NPFARMA                                    ', 1 ,'Via Bellini, 26/28                                        ', '          ', 'AV ', 'revocato in data 05/10/06   ', '15/N,23/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Grottaminarda                         ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'NPFARMA                                    ', 1 ,'Via Bellini, 26/28                                        ', '          ', 'AV ', 'revocato in data 05/10/06   ', '           ', 0.0, 0.0, '          ', '15/V.20/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Grottaminarda                         ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'SANNIOVET                                  ', 1 ,'Via Nazionale                                             ', '          ', 'AV ', 'revovato in data 05/08/2009', '15/S.34/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, '                                      ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'SANNIOVET                                  ', 1 ,'Via Nazionale                                             ', '          ', 'AV ', 'revocato in data ', '           ', 0.0, 0.0, '          ', '15/S.22/v ', '2010-11-04', 291, '2010-11-04', 291, null, '                                      ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'So. Farma.Morra                            ', 2 ,'Via Capozzi,22/24                                         ', '22/04/2002', 'AV ', '        ', '15/S.5/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Avellino                              ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'La Veterinaria srl                         ', 2 ,'Via Appia, 87                                             ', '02/12/2009', 'AV ', '        ', '15/V.36/g  ', 0.0, 0.0, '02/12/2009', '15/V.24/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Atripalda                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Soc.D.ri Sabato & C.Farmaceutici srl       ', 2 ,'                                                          ', '07/05/1993', '   ', '        ', '15/S.10/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, '                                      ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Dott.Ragucci Massimo                       ', 3 ,'Via Piano dello Stallone snc                              ', '22/07/1998', 'BN ', '        ', '15/R.26/g  ', 0.0, 0.0, '          ', '15/R.26/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'S.Giorgio la Molara                   ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Federico Manna srl                         ', 3 ,'Via S.Gaspare del Bufalo 1/5/7                            ', '20/10/1994', 'BN ', '        ', '15/M.12/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Benevento                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Svima farmaceutici srl                     ', 3 ,'C.da Panomorra                                            ', '15/05/1995', 'BN ', 'sospeso ', '15/S.14/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Benevento                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Unifarma soc. coop arl                     ', 3 ,'Via Corte Nocera snc                                      ', '15/05/1995', 'BN ', '        ', '15/U.29/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'S.Salvatore Telesino                  ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Farmacia Veterinaria                       ', 3 ,'Contrada Cuffaro                                          ', '16/03/2007', 'BN ', '        ', '15/F.30/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Morcone                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'VITALZOO                                   ', 3 ,'Via Roma, 32                                              ', '          ', 'BN ', 'revocato in data 28/02/2007', '15/V.29/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Morcone                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'VITALZOO                                   ', 3 ,'Via Roma, 32                                              ', '          ', 'BN ', 'revocato in data 28/02/2007', '           ', 0.0, 0.0, '          ', '15/S15.V  ', '2010-11-04', 291, '2010-11-04', 291, null, 'Morcone                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Euroveterinaria srl                        ', 4 ,'Via S.Ferdinando 1                                        ', '17/12/2001', 'CE ', '        ', '15/E21/G   ', 0.0, 0.0, '21/12/2001', '15/E.21v  ', '2010-11-04', 291, '2010-11-04', 291, null, 'Alvignano                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Profarmaco                                 ', 4 ,'Via Bologna,22                                            ', '02/01/2002', 'CE ', '        ', '15/P.2/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Casagiove                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Biofarma srl                               ', 4 ,'Via Pontone                                               ', '13/07/1993', 'CE ', '        ', '15/B.4/G   ', 0.0, 0.0, '13/07/1993', '15/B.4/v  ', '2010-11-04', 291, '2010-11-04', 291, null, 'localita' Puccianiello Caserta         ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Galenitalia                                ', 4 ,'Via Passionisti,15                                        ', '15/07/1999', 'CE ', 'revocato', '15/G.37//g ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Casagiove                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Dell''Aquila Veterinaria                   ', 4 ,'Via Patturelli 16/18                                      ', '28/07/1994', 'CE ', '        ', '15/D.13/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Caserta                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'EMX2 Srl                                   ', 4 ,'Via Gramsci 100                                           ', '02/12/1999', 'CE ', '        ', '15/E.22/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'S.Felice a Cancello                   ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'AGRIZOO FARM                               ', 4 ,'Via veneto, 39                                            ', '24/03/1993', 'CE ', '        ', '15/A.66/g  ', 0.0, 0.0, '04/01/1994', '15/A.66/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Marcianise                            ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Neifarma L. spa                            ', 4 ,'Via pasionisti 15                                         ', '01/03/1995', 'CE ', '        ', '15/N.7/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Casagiove                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Italia Vet                                 ', 4 ,'Via S.S.Riardo                                            ', '22/12/2005', 'CE ', '        ', '15/I.18/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Caserta                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'VETZOO                                     ', 4 ,'Via Provinciale Riardo                                    ', '22/02/2008', 'CE ', 'revocato', '15/V.32/g  ', 0.0, 0.0, '02/04/2008', '15/v.21/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Petramelara Riardo                    ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Farmavetersud                              ', 4 ,'Piazza Roma, 4                                            ', '04/05/2010', 'CE ', '        ', '15/V.37/g  ', 0.0, 0.0, '12/05/2010', '15/V.25/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Capriati a Volturno                   ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), '                                           ', 4 ,'                                                          ', '          ', '   ', '        ', '           ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, '                                      ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'CIB FARM                                   ', 4 ,'Via SS 158 dir Sud,31                                     ', '          ', 'CE ', '        ', '15/C.35/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Piedimonte Matese                     ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'CIB FARM                                   ', 4 ,'Via SS 158 dir Sud,31                                     ', '          ', 'CE ', '        ', '           ', 0.0, 0.0, '16/10/2009', '15/C.33/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Piedimonte Matese                     ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'SO.FARMA.MORRA SPA                         ', 5 ,'Via Nazionale Appia 86                                    ', '24/04/1993', 'CE ', '        ', '157S.3/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Curti                                 ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Farmavet srl                               ', 5 ,'Via Cupa,2                                                ', '24/05/1999', 'CE ', '        ', '15/F.146/g ', 0.0, 0.0, '          ', '15/F.146/v', '2010-11-04', 291, '2010-11-04', 291, null, 'Grazzanise                            ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'ZOOVET srl                                 ', 5 ,'Via Roma per Cappella Reale, 79                           ', '          ', 'CE ', '        ', '15/Z.54/g  ', 0.0, 0.0, '          ', '15/Z.54/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Cancello Arnone                       ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'VET FARM S.R.L.                            ', 5 ,'Via Roma, 251                                             ', '20/04/2005', '   ', '        ', '           ', 0.0, 0.0, '          ', '15/V 16/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Cancello ed Arnone                    ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'VETERFARM                                  ', 5 ,'Via Nazionale Appia km200                                 ', '          ', 'CE ', '        ', '15/V.12/g  ', 0.0, 0.0, '07/06/2006', '15/V.12/V ', '2010-11-04', 291, '2010-11-04', 291, null, 'Capua                                 ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Comifar distributore SPA                   ', 5 ,'Via Consortile zona industriale                           ', '          ', 'CE ', '        ', '15/C.25/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Carinaro                              ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Valle dell''Orso Green Point Mixer 2000 srl', 6 ,'Via Ferrante Imparato 192                                 ', '20/10/1994', 'NA ', '        ', '15/V.67/g  ', 0.0, 0.0, '11/01/1995', '15/V.67/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Napoli                                ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'EQUIVET SUD                                ', 6 ,'Via R. Ruggiero 14/bis                                    ', '16/03/1993', 'NA ', '        ', '15/E.6/g   ', 0.0, 0.0, '14/02/1994', '15/E.6/V  ', '2010-11-04', 291, '2010-11-04', 291, null, 'Napoli                                ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Galenitalia SPA                            ', 6 ,'Via Luigi Volpicella,32                                   ', '15/07/1999', 'NA ', '        ', '15/G.39/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Napoli                                ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Diemmeci srl                               ', 6 ,'Via G.Quagliariello,27                                    ', '22/02/1994', 'NA ', '        ', '15/D.16/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Napoli                                ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Dal Re G.B.                                ', 6 ,'Via Manzoni 26/a                                          ', '07/05/1993', 'NA ', '        ', '15/D.19/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Napoli                                ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'For-Vet di Acerbo Anna                     ', 6 ,'Via Raffaele Ruggero18/c                                  ', '16/03/1993', 'NA ', '        ', '15/F.77/g  ', 0.0, 0.0, '05/04/1994', '157F.77/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Agnani di Napoli                      ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'SO.FARMA.MORRA SPA                         ', 6 ,'Via provinciale delle Brecce,51                           ', '20/05/1993', 'NA ', '        ', '15/S.33/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Napoli                                ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Farmaceutici Aristide Tonacci srl          ', 7 ,'Circonv.Esterna 41/43                                     ', '02/03/1998', 'NA ', '        ', '15/F.124/g ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Mugnano di Napoli                     ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Futura srl                                 ', 7 ,'Via S. Nollo 62/64                                        ', '30/07/1999', 'NA ', '        ', '15/F.78/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Giugliano                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Logistica Farmaceutica                     ', 7 ,'Strada Prov. Pianura                                      ', '19/04/2010', 'NA ', '        ', '15/L.37/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Pozzuoli                              ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'VETER SHOP                                 ', 7 ,'Via Lago Patria 184                                       ', '          ', 'NA ', '        ', '           ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Giugliano                             ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Tarantino Paolo e Co. Medicinali snc       ', 8 ,'                                                          ', '14/05/1993', 'NA ', '        ', '15/T.5/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Frattamaggiore                        ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Cemon srl                                  ', 8 ,'Via E.fermi                                               ', '          ', 'NA ', '        ', '           ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Grumo Nevano                          ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Farvima                                    ', 8 ,'                                                          ', '05/05/2006', 'NA ', '        ', '15/F.21/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, '                                      ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Vital zoo                                  ', 8 ,'Via P.M.Vergara 72                                        ', '01/06/2006', 'NA ', '        ', '15.v/22/g  ', 0.0, 0.0, '08/06/2006', '15/V.10/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Frattamaggiore                        ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Comifar distributore SPA                   ', 8 ,'Via Marconi                                               ', '          ', 'NA ', '        ', '15/A.4/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Casavatore                            ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Guacci Spa                                 ', 9 ,'CIS di Nola Is 8 n.8092/95                                ', '24/03/1993', 'NA ', '        ', '15/G.7/g   ', 0.0, 0.0, '11/01/1995', '15/G.7/v  ', '2010-11-04', 291, '2010-11-04', 291, null, 'Nola                                  ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'SO.FARMA.MORRA SPA                         ', 9 ,'CIS di Nola Is 8 n.8092/95                                ', '92/02/99  ', 'NA ', '        ', '15/S.93/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Nola                                  ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'SO.FARMA.MORRA SPA                         ', 9 ,'CIS di Nola Is 8 n.8092/95                                ', '23/05/2002', 'NA ', '        ', '15/S.7/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Nola                                  ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Cofarmi farmacisti insieme spa             ', 9 ,'interporto di nola zona asi lotto d1 blocco A1 civ 137/140', '04/05/2007', 'NA ', '        ', '15/C.31/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Nola                                  ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'La Veterinaria srl                         ', 9 ,'Via Reg.Margherita 39                                     ', '13/04/1993', 'NA ', '        ', '15/L.28/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'S.Anastasia                           ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Farmacampania Soc.Coop Arl                 ', 9 ,'CIS di Nola Is 8 n.8036/8037                              ', '23/03/2006', 'NA ', '        ', 'F.15/F.20/g', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Nola                                  ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'CE.DI.FAR. Srl                             ', 9 ,'Via Nuova ponte delle Tavole                              ', '23/09/1996', 'NA ', '        ', '15/C.27/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'S.Vitaliano                           ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'FARDEA Spa                                 ', 9 ,'Via Naz. Delle Puglie Km 36,400                           ', '07/05/1993', 'NA ', '        ', '15/F.10/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Casalnuovo                            ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'SO.FARMA.MORRA SPA                         ', 9 ,'CIS di Nola Is 1 n. 134                                   ', '05/10/1993', 'NA ', '        ', '15/S.1/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Nola                                  ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Dalvet srl                                 ', 9 ,'Via S.M. del Pozzo 5/C                                    ', '07/04/1995', 'NA ', '        ', '15/D.30/g  ', 0.0, 0.0, '15/05/1995', '15/D.30/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Somma vesuviana                       ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Nocefarm snc                               ', 9 ,'Via Costantinopoli 142                                    ', '23/06/1995', 'NA ', '        ', '15/N.21/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Piazzolla di Nola                     ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Natella dr Carlo srl                       ', 9 ,'Via Madonnelle 14                                         ', '22/02/1994', 'NA ', '        ', '15/N.29/g  o', 0.0, 0.0,'          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Castello di Cisterna Pomigliano d''arco', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'S.I.V.A.S. Italia spa                      ', 9 ,'Via trentola                                              ', '19/01/1998', 'NA ', '        ', '15/S.88/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Somma Vesuviana                       ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Laboratorio Vaccinogeno Paganini snc       ', 10,'Via Diaz 147/149                                          ', '09/10/2000', 'NA ', '        ', '15/L.43/g  ', 0.0, 0.0, '17/10/2000', '15/L.43/V ', '2010-11-04', 291, '2010-11-04', 291, null, 'Portici                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Centro Agroveta Campania                   ', 11,'Via nazionale 188                                         ', '04/01/1993', 'SA ', '        ', '15/C.96/g  ', 0.0, 0.0, '23/07/1993', '15/C.96/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Scafati Cortile di Palma              ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'De Pascale Annibale                        ', 11,'Via della Liberta' 78                                      ', '22/10/1996', 'SA ', '        ', '15/D.32/g  ', 0.0, 0.0, '08/11/1996', '15/D.32/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Roccapiemonte                         ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Veterfarm srl                              ', 11,'Via trieste, 11                                           ', '09/06/1993', 'SA ', 'revocato in data 29/05/2009', '15/V.27/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Castel san Giorgio                    ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Veterfarm srl                              ', 11,'Via trieste, 11                                           ', '02/02/1999', 'SA ', 'revocato in data 29/05/2009', '           ', 0.0, 0.0, '          ', '15/V.27/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Castel san Giorgio                    ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Veterinaria 2000                           ', 12,'Parco Europa 92 SS 18                                     ', '15/11/2001', 'SA ', '        ', '15/V.1/g   ', 0.0, 0.0, '22/11/2001', '15/V.1/V  ', '2010-11-04', 291, '2010-11-04', 291, null, 'Contrada Pagliarone                   ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'FARMAS srl                                 ', 12,'Via Costanzella Calenda,2                                 ', '27/02/2002', 'SA ', '        ', '15/F.3/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'FARVINA Medicinali spa                     ', 12,'Via Vesola Fuorni                                         ', '09/02/1996', 'SA ', '        ', '15/F.21/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Galenitalia spa                            ', 12,'Via Zona della Porta 7                                    ', '15/07/1999', 'SA ', '        ', '15/G.35/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'V.I.M srl                                  ', 12,'Via Costanzella Calenda,2                                 ', '08/05/2002', 'SA ', '        ', '15/V.6/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'PUMA FARM srl                              ', 12,'Via S.Leonardo 120                                        ', '19/06/2002', 'SA ', '        ', '15/P.8/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Medivet                                    ', 12,'Via M.Alfani 80                                           ', '29/04/1993', 'SA ', '        ', '15/M.5/g   ', 0.0, 0.0, '29/10/1994', '15/M.5/v  ', '2010-11-04', 291, '2010-11-04', 291, null, 'Pontecagnano-Faiano                   ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Novafarma srl                              ', 12,'                                                          ', '21/11/1994', 'SA ', '        ', '15/N.1/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Neofarma spa                               ', 12,'Via della Porta                                           ', '07/10/1996', 'SA ', '        ', '15/N.38/g  ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), '3 D Disinfettanti srl                      ', 12,'Via Wenner 20/a                                           ', '29/11/1994', 'SA ', '        ', '15/T.14/g  ', 0.0, 0.0, '13/02/1995', '15/T.14/v ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Zoofarmas snc                              ', 12,'Via Acquasanta Z.I.                                       ', '13/07/1993', 'SA ', '        ', '15/Z 9/g   ', 0.0, 0.0, '          ', '          ', '2010-11-04', 291, '2010-11-04', 291, null, 'Salerno                               ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Medivet                                    ', 12,'Via Alfani 80                                             ', '          ', 'SA ', '        ', '           ', 0.0, 0.0, '04/01/1994', '15/Z.9/v  ', '2010-11-04', 291, '2010-11-04', 291, null, 'Pontecagnano                          ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Marvet                                     ', 12,'Via Ponte Barizzo                                         ', '03/04/2003', 'SA ', '        ', '15/M.13/g  ', 0.0, 0.0, '20/09/2005', '15/M.13/V ', '2010-11-04', 291, '2010-11-04', 291, null, 'Capaccio Scalo                        ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Zoomedical del Dr.Cobellis De Feo e C.     ', 13,'Contr. Malagenia Z.I.                                     ', '02/12/1996', 'SA ', '        ', '15/Z.26/g  ', 0.0, 0.0, '09/12/1996', '15/Z.26/V ', '2010-11-04', 291, '2010-11-04', 291, null, 'Ogliastro Cilento                     ', 0);
INSERT INTO farmacie(id_farmacia, ragione_sociale, site_id, indirizzo, "citta'", provincia, stato, postalcode, latitude, longitude, note1, note2, entered, enteredby, modified, modifiedby, trashed_date, citta, id_prescrizione)VALUES (nextval('farmacia_id_seq'), 'Zoomedica Cilentana sas                    ', 13,'Via Rettifilo 11713                                       ', '27/03/1998', 'SA ', '        ', '15/Z.57/g  ', 0.0, 0.0, '20/04/1998', '15/Z.57/V ', '2010-11-04', 291, '2010-11-04', 291, null, 'Capaccio                              ', 0);
