
package it.izs.apicoltura.apimovimentazione.ws;

import it.izs.apicoltura.apianagraficaattivita.ws.ConfiguratoreServizi;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.aspcfs.modules.util.imports.ApplicationProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApiingEndpointService", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", wsdlLocation = ConfiguratoreServizi.END_POINT+"ws/apicoltura/apimovimentazione/ingresso?wsdl")
public class ApiingEndpointService
    extends Service
{

    private final static URL APIINGENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException APIINGENDPOINTSERVICE_EXCEPTION;
    private final static QName APIINGENDPOINTSERVICE_QNAME = new QName("http://ws.apimovimentazione.apicoltura.izs.it/", "ApiingEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL( ApplicationProperties.getProperty("END_POINT_BDAPI")+"ws/apicoltura/apimovimentazione/ingresso?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APIINGENDPOINTSERVICE_WSDL_LOCATION = url;
        APIINGENDPOINTSERVICE_EXCEPTION = e;
    }

    public ApiingEndpointService() {
        super(__getWsdlLocation(), APIINGENDPOINTSERVICE_QNAME);
    }

    public ApiingEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APIINGENDPOINTSERVICE_QNAME, features);
    }

    public ApiingEndpointService(URL wsdlLocation) {
        super(wsdlLocation, APIINGENDPOINTSERVICE_QNAME);
    }

    public ApiingEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APIINGENDPOINTSERVICE_QNAME, features);
    }

    public ApiingEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiingEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApiingEndpoint
     */
    @WebEndpoint(name = "ApiingEndpointPort")
    public ApiingEndpoint getApiingEndpointPort() {
        return super.getPort(new QName("http://ws.apimovimentazione.apicoltura.izs.it/", "ApiingEndpointPort"), ApiingEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiingEndpoint
     */
    @WebEndpoint(name = "ApiingEndpointPort")
    public ApiingEndpoint getApiingEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.apimovimentazione.apicoltura.izs.it/", "ApiingEndpointPort"), ApiingEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APIINGENDPOINTSERVICE_EXCEPTION!= null) {
            throw APIINGENDPOINTSERVICE_EXCEPTION;
        }
        System.out.println("##API WSDL LOCATION -->"+APIINGENDPOINTSERVICE_WSDL_LOCATION);
        return APIINGENDPOINTSERVICE_WSDL_LOCATION;
    }

}
