
package it.izs.apicoltura.apimovimentazione.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApimodmovEndpoint", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApimodmovEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apimovimentazione.ws.InsertApimodmovResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertApimodmovResponse", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/insertApimodmovRequest", output = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/insertApimodmovResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/insertApimodmov/Fault/BusinessWsException")
    })
    public InsertApimodmovResponse insertApimodmov(
        @WebParam(name = "insertApimodmov", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "parameters")
        InsertApimodmov parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apimovimentazione.ws.UpdateApimodmovResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateApimodmovResponse", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/updateApimodmovRequest", output = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/updateApimodmovResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/updateApimodmov/Fault/BusinessWsException")
    })
    public UpdateApimodmovResponse updateApimodmov(
        @WebParam(name = "updateApimodmov", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "parameters")
        UpdateApimodmov parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apimovimentazione.ws.DeleteApimodmovResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteApimodmovResponse", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/deleteApimodmovRequest", output = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/deleteApimodmovResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/deleteApimodmov/Fault/BusinessWsException")
    })
    public DeleteApimodmovResponse deleteApimodmov(
        @WebParam(name = "deleteApimodmov", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "parameters")
        DeleteApimodmov parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apimovimentazione.ws.SearchApimodmovResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchApimodmovResponse", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/searchApimodmovRequest", output = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/searchApimodmovResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/searchApimodmov/Fault/BusinessWsException")
    })
    public SearchApimodmovResponse searchApimodmov(
        @WebParam(name = "searchApimodmov", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "parameters")
        SearchApimodmov parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apimovimentazione.ws.SearchApimodmovByPkResponse
     */
    @WebMethod
    @WebResult(name = "searchApimodmovByPkResponse", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/searchApimodmovByPkRequest", output = "http://ws.apimovimentazione.apicoltura.izs.it/ApimodmovEndpoint/searchApimodmovByPkResponse")
    public SearchApimodmovByPkResponse searchApimodmovByPk(
        @WebParam(name = "searchApimodmovByPk", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", partName = "parameters")
        SearchApimodmovByPk parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apimovimentazione.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

}
