
package it.izs.apicoltura.apianagraficaazienda.ws;

import it.izs.apicoltura.apianagraficaattivita.ws.ConfiguratoreServizi;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.aspcfs.modules.util.imports.ApplicationProperties;
import org.json.JSONObject;

import configurazione.centralizzata.nuova.gestione.ClientServizioCentralizzato;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApiaziendaEndpointService", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", wsdlLocation = ConfiguratoreServizi.END_POINT+"ws/apicoltura/apianagrafica/apiazienda?wsdl")
public class ApiaziendaEndpointService
    extends Service
{

    private final static URL APIAZIENDAENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException APIAZIENDAENDPOINTSERVICE_EXCEPTION;
    private final static QName APIAZIENDAENDPOINTSERVICE_QNAME = new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiaziendaEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	if(ApplicationProperties.getProperty("recupero_wsdl_locale").equals("true"))
        	{
        		ClientServizioCentralizzato sclient = new ClientServizioCentralizzato();
        		JSONObject mappaEndPoints = sclient.getMappaEndpointsSca();
        		String urlGisa = null;
				if(mappaEndPoints.has("gisa_lan")){
					urlGisa = mappaEndPoints.getString("gisa_lan");

				}
					if(urlGisa==null || urlGisa.equals(""))
        			urlGisa = mappaEndPoints.getString("gisa");
				
        		url = new URL(urlGisa + "/" + ApplicationProperties.getProperty("END_POINT_BDAPI_LOCALE_AZIENDA"));
        	}
        	else
        		url =  new URL(ApplicationProperties.getProperty("END_POINT_BDAPI")+"ws/apicoltura/apianagrafica/apiazienda?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        APIAZIENDAENDPOINTSERVICE_WSDL_LOCATION = url;
        APIAZIENDAENDPOINTSERVICE_EXCEPTION = e;
    }

    public ApiaziendaEndpointService() {
        super(__getWsdlLocation(), APIAZIENDAENDPOINTSERVICE_QNAME);
    }

    public ApiaziendaEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APIAZIENDAENDPOINTSERVICE_QNAME, features);
    }

    public ApiaziendaEndpointService(URL wsdlLocation) {
        super(wsdlLocation, APIAZIENDAENDPOINTSERVICE_QNAME);
    }

    public ApiaziendaEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APIAZIENDAENDPOINTSERVICE_QNAME, features);
    }

    public ApiaziendaEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiaziendaEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApiaziendaEndpoint
     */
    @WebEndpoint(name = "ApiaziendaEndpointPort")
    public ApiaziendaEndpoint getApiaziendaEndpointPort() {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiaziendaEndpointPort"), ApiaziendaEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiaziendaEndpoint
     */
    @WebEndpoint(name = "ApiaziendaEndpointPort")
    public ApiaziendaEndpoint getApiaziendaEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiaziendaEndpointPort"), ApiaziendaEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APIAZIENDAENDPOINTSERVICE_EXCEPTION!= null) {
            throw APIAZIENDAENDPOINTSERVICE_EXCEPTION;
        }
        System.out.println("##API WSDL LOCATION -->"+APIAZIENDAENDPOINTSERVICE_WSDL_LOCATION);
        return APIAZIENDAENDPOINTSERVICE_WSDL_LOCATION;
    }

}
