
package it.izs.apicoltura.apianagraficaazienda.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApiaziendaEndpoint", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApiaziendaEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagrafica.ws.InsertApiAziendaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertApiAziendaResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/insertApiAziendaRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/insertApiAziendaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/insertApiAzienda/Fault/BusinessWsException")
    })
    public InsertApiAziendaResponse insertApiAzienda(
        @WebParam(name = "insertApiAzienda", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        InsertApiAzienda parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagrafica.ws.UpdateApiAziendaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateApiAziendaResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/updateApiAziendaRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/updateApiAziendaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/updateApiAzienda/Fault/BusinessWsException")
    })
    public UpdateApiAziendaResponse updateApiAzienda(
        @WebParam(name = "updateApiAzienda", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        UpdateApiAzienda parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagrafica.ws.DeleteApiAziendaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteApiAziendaResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/deleteApiAziendaRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/deleteApiAziendaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/deleteApiAzienda/Fault/BusinessWsException")
    })
    public DeleteApiAziendaResponse deleteApiAzienda(
        @WebParam(name = "deleteApiAzienda", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        DeleteApiAzienda parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagrafica.ws.SearchApiAziendaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchApiAziendaResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/searchApiAziendaRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/searchApiAziendaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/searchApiAzienda/Fault/BusinessWsException")
    })
    public SearchApiAziendaResponse searchApiAzienda(
        @WebParam(name = "searchApiAzienda", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiAzienda parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagrafica.ws.ElencoCodiciDisponibiliResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "elencoCodiciDisponibiliResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/elencoCodiciDisponibiliRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/elencoCodiciDisponibiliResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/elencoCodiciDisponibili/Fault/BusinessWsException")
    })
    public ElencoCodiciDisponibiliResponse elencoCodiciDisponibili(
        @WebParam(name = "elencoCodiciDisponibili", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        ElencoCodiciDisponibili parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagrafica.ws.ElencoCodiciAssegnatiResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "elencoCodiciAssegnatiResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/elencoCodiciAssegnatiRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/elencoCodiciAssegnatiResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/elencoCodiciAssegnati/Fault/BusinessWsException")
    })
    public ElencoCodiciAssegnatiResponse elencoCodiciAssegnati(
        @WebParam(name = "elencoCodiciAssegnati", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        ElencoCodiciAssegnati parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagrafica.ws.SearchApiAziendaByPkResponse
     */
    @WebMethod
    @WebResult(name = "searchApiAziendaByPkResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/searchApiAziendaByPkRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiaziendaEndpoint/searchApiAziendaByPkResponse")
    public SearchApiAziendaByPkResponse searchApiAziendaByPk(
        @WebParam(name = "searchApiAziendaByPk", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiAziendaByPk parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

}
