
package it.izs.sinsa.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "prelievi", targetNamespace = "http://sinsa.izs.it/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Prelievi {


    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.sinsa.services.PrintSchedaPrelievoResponse
     * @throws SOAPException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "printSchedaPrelievoResponse", targetNamespace = "http://sinsa.izs.it/services", partName = "result")
    @Action(input = "http://sinsa.izs.it/services/prelievi/printSchedaPrelievoRequest", output = "http://sinsa.izs.it/services/prelievi/printSchedaPrelievoResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/printSchedaPrelievo/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/printSchedaPrelievo/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/printSchedaPrelievo/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://sinsa.izs.it/services/prelievi/printSchedaPrelievo/Fault/Exception")
    })
    public PrintSchedaPrelievoResponse printSchedaPrelievo(
        @WebParam(name = "printSchedaPrelievo", targetNamespace = "http://sinsa.izs.it/services", partName = "parameters")
        PrintSchedaPrelievo parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.sinsa.services.UploadSchedaPrelievoFirmataResponse
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     * @throws BusinessException_Exception
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadSchedaPrelievoFirmataResponse", targetNamespace = "http://sinsa.izs.it/services", partName = "result")
    @Action(input = "http://sinsa.izs.it/services/prelievi/uploadSchedaPrelievoFirmataRequest", output = "http://sinsa.izs.it/services/prelievi/uploadSchedaPrelievoFirmataResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/uploadSchedaPrelievoFirmata/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/uploadSchedaPrelievoFirmata/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/uploadSchedaPrelievoFirmata/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://sinsa.izs.it/services/prelievi/uploadSchedaPrelievoFirmata/Fault/Exception")
    })
    public UploadSchedaPrelievoFirmataResponse uploadSchedaPrelievoFirmata(
        @WebParam(name = "uploadSchedaPrelievoFirmata", targetNamespace = "http://sinsa.izs.it/services", partName = "parameters")
        UploadSchedaPrelievoFirmata parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.sinsa.services.SearchPrelievoResponse
     * @throws SOAPException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchPrelievoResponse", targetNamespace = "http://sinsa.izs.it/services", partName = "result")
    @Action(input = "http://sinsa.izs.it/services/prelievi/searchPrelievoRequest", output = "http://sinsa.izs.it/services/prelievi/searchPrelievoResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/searchPrelievo/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/searchPrelievo/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/searchPrelievo/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://sinsa.izs.it/services/prelievi/searchPrelievo/Fault/Exception")
    })
    public SearchPrelievoResponse searchPrelievo(
        @WebParam(name = "searchPrelievo", targetNamespace = "http://sinsa.izs.it/services", partName = "parameters")
        SearchPrelievo parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.sinsa.services.SearchPrelievoByIdResponse
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     * @throws BusinessException_Exception
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchPrelievoByIdResponse", targetNamespace = "http://sinsa.izs.it/services", partName = "result")
    @Action(input = "http://sinsa.izs.it/services/prelievi/searchPrelievoByIdRequest", output = "http://sinsa.izs.it/services/prelievi/searchPrelievoByIdResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/searchPrelievoById/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/searchPrelievoById/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/searchPrelievoById/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://sinsa.izs.it/services/prelievi/searchPrelievoById/Fault/Exception")
    })
    public SearchPrelievoByIdResponse searchPrelievoById(
        @WebParam(name = "searchPrelievoById", targetNamespace = "http://sinsa.izs.it/services", partName = "parameters")
        SearchPrelievoById parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.sinsa.services.UpdateAccettazioneResponse
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     * @throws BusinessException_Exception
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateAccettazioneResponse", targetNamespace = "http://sinsa.izs.it/services", partName = "result")
    @Action(input = "http://sinsa.izs.it/services/prelievi/updateAccettazioneRequest", output = "http://sinsa.izs.it/services/prelievi/updateAccettazioneResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/updateAccettazione/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/updateAccettazione/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/updateAccettazione/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://sinsa.izs.it/services/prelievi/updateAccettazione/Fault/Exception")
    })
    public UpdateAccettazioneResponse updateAccettazione(
        @WebParam(name = "updateAccettazione", targetNamespace = "http://sinsa.izs.it/services", partName = "parameters")
        UpdateAccettazione parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.sinsa.services.InsertPrelievoResponse
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     * @throws BusinessException_Exception
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertPrelievoResponse", targetNamespace = "http://sinsa.izs.it/services", partName = "result")
    @Action(input = "http://sinsa.izs.it/services/prelievi/insertPrelievoRequest", output = "http://sinsa.izs.it/services/prelievi/insertPrelievoResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/insertPrelievo/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/insertPrelievo/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/insertPrelievo/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://sinsa.izs.it/services/prelievi/insertPrelievo/Fault/Exception")
    })
    public InsertPrelievoResponse insertPrelievo(
        @WebParam(name = "insertPrelievo", targetNamespace = "http://sinsa.izs.it/services", partName = "parameters")
        InsertPrelievo parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.sinsa.services.DownloadSchedaPrelievoFirmataResponse
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     * @throws BusinessException_Exception
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadSchedaPrelievoFirmataResponse", targetNamespace = "http://sinsa.izs.it/services", partName = "result")
    @Action(input = "http://sinsa.izs.it/services/prelievi/downloadSchedaPrelievoFirmataRequest", output = "http://sinsa.izs.it/services/prelievi/downloadSchedaPrelievoFirmataResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/downloadSchedaPrelievoFirmata/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/downloadSchedaPrelievoFirmata/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://sinsa.izs.it/services/prelievi/downloadSchedaPrelievoFirmata/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://sinsa.izs.it/services/prelievi/downloadSchedaPrelievoFirmata/Fault/Exception")
    })
    public DownloadSchedaPrelievoFirmataResponse downloadSchedaPrelievoFirmata(
        @WebParam(name = "downloadSchedaPrelievoFirmata", targetNamespace = "http://sinsa.izs.it/services", partName = "parameters")
        DownloadSchedaPrelievoFirmata parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://sinsa.izs.it/services", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    

   
    

    
  

}
