package it.us.web.bean.vam;

import it.us.web.bean.vam.lookup.LookupAutopsiaEsitiEsami;
import it.us.web.bean.vam.lookup.LookupAutopsiaOrgani;
import it.us.web.bean.vam.lookup.LookupAutopsiaTipiEsami;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
* ExtNodoFilieraProdottoId generated by hbm2java
*/
@Embeddable
public class AutopsiaOrganiTipiEsamiEsitiId implements java.io.Serializable {

	private LookupAutopsiaOrgani organo;
	private LookupAutopsiaTipiEsami tipoEsame;
	private LookupAutopsiaEsitiEsami esito;

	
	public AutopsiaOrganiTipiEsamiEsitiId(){}
	
	
	public AutopsiaOrganiTipiEsamiEsitiId(LookupAutopsiaOrgani organo, LookupAutopsiaTipiEsami tipoEsame,LookupAutopsiaEsitiEsami esito) {
		this.organo = organo;
		this.tipoEsame = tipoEsame;
		this.esito = esito;
	}

	@Column(name = "organo", nullable = false)
	public LookupAutopsiaOrgani getOrgano() {
		return this.organo;
	}

	public void setOrgano(LookupAutopsiaOrgani organo) {
		this.organo = organo;
	}

	@Column(name = "tipoEsame", nullable = false)
	public LookupAutopsiaTipiEsami getTipo() {
		return this.tipoEsame;
	}

	public void setTipo(LookupAutopsiaTipiEsami tipoEsame) {
		this.tipoEsame = tipoEsame;
	}
	
	@Column(name = "esito", nullable = false)
	public LookupAutopsiaEsitiEsami getEsito() {
		return this.esito;
	}

	public void setEsito(LookupAutopsiaEsitiEsami esito) {
		this.esito = esito;
	}


	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutopsiaOrganiTipiEsamiEsitiId))
			return false;
		AutopsiaOrganiTipiEsamiEsitiId castOther = (AutopsiaOrganiTipiEsamiEsitiId) other;

		return (this.getEsito() == castOther.getEsito())
				&& (this.getTipo() == castOther.getTipo())
				&& (this.getOrgano() == castOther.getOrgano());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getOrgano().getId();
		result = 37 * result + (int) this.getTipo().getId();
		result = 37 * result + (int) this.getEsito().getId();
		return result;
	}

}

