--Controllare le funzioni e le viste se sono allineate con ufficiale
--In Sinac va propagato ciò che in Vam e Bdu non ci va? toelettatura, strutture veterinarie private
--Controllare se quelle già presenti in Gisa-Bdu-Vam sono coerenti con questi flag. Attività da fare quando si farò il resoconto di cosa sta in Gisa-Bdu-Vam-Sinac

--lanciato in ufficiale il 13/05 e 14/05
--ML11
ALTER TABLE master_list_flag_linee_attivita drop column codice_tipologia_struttura_sinac;
ALTER TABLE master_list_flag_linee_attivita ADD sinac_codice_struttura_detenzione varchar NULL;
ALTER TABLE master_list_flag_linee_attivita ADD sinac_codice_struttura_veterinaria varchar NULL;
ALTER TABLE master_list_flag_linee_attivita ADD bdu_canile boolean;
ALTER TABLE master_list_flag_linee_attivita ADD bdu_operatore_commerciale boolean;

update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'ALLEVAMENTO DI ANIMALI, PER IL QUALE E'' NECESSARIO IL CODICE AZIENDALE BDN, MUNITO DI SCORTA DI FARMACI VETERINARI' and attivita ilike 'CON SCORTA AD USO DEL O DEI PROPRI ALLEVAMENTI SITI ALL''INTERNO DI UN''UNICA AZIENDA' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'CONCENTRAMENTO DI ANIMALI, PER IL QUALE NON E'' NECESSARIO IL CODICE AZIENDALE BDN, MUNITO DI SCORTA DI FARMACI VETERINARI' and attivita ilike 'CONCENTRAMENTO DI ANIMALI, PER IL QUALE NON E'' NECESSARIO IL CODICE AZIENDALE BDN, MUNITO DI SCORTA DI FARMACI VETERINARI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'COMMERCIO ALL''INGROSSO' and attivita ilike 'COMMERCIO ALL''INGROSSO SENZA VENDITA AL DETTAGLIO (ART.66) IN LOCALI CON SUPERFICIE TOTALE LORDA COMPRENSIVA DI SERVIZI E DEPOSITI INFERIORE A 400 MQ' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'COMMERCIO ALL''INGROSSO' and attivita ilike 'COMMERCIO ALL''INGROSSO SENZA VENDITA AL DETTAGLIO (ART.66) IN LOCALI CON SUPERFICIE TOTALE LORDA COMPRENSIVA DI SERVIZI E DEPOSITI SUPERIORE A 400 MQ' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'COMMERCIO ALL''INGROSSO' and attivita ilike 'COMMERCIO ALL''INGROSSO CON VENDITA AL DETTAGLIO (ART. 66 + ART. 70 punto 2) IN LOCALI CON SUPERFICIE TOTALE LORDA COMPRENSIVA DI SERVIZI E DEPOSITI INFERIORE A 400 MQ' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'COMMERCIO ALL''INGROSSO' and attivita ilike 'COMMERCIO ALL''INGROSSO CON VENDITA AL DETTAGLIO (ART. 66 + ART. 70 punto 2) IN LOCALI CON SUPERFICIE TOTALE LORDA COMPRENSIVA DI SERVIZI E DEPOSITI SUPERIORE A 400 MQ' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'MEDICO VETERINARIO MUNITO DI SCORTA DI FARMACI VETERINARI PER ATTIVITA'' ZOOIATRICA' and attivita ilike 'MEDICO VETERINARIO MUNITO DI SCORTA DI FARMACI VETERINARI PER ATTIVITA'' ZOOIATRICA' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'ESERCIZIO DI VENDITA AL DETTAGLIO CHE EFFETTUA LA VENDITA DI FARMACI VETERINARI' and attivita ilike 'ESERCIZIO DI VICINATO CHE EFFETTUA LA VENDITA DI FARMACI VETERINARI (ART. 70 PUNTO 1)' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'ESERCIZIO DI VENDITA AL DETTAGLIO CHE EFFETTUA LA VENDITA DI FARMACI VETERINARI' and attivita ilike 'GRANDE STRUTTURA DI VENDITA CHE EFFETTUA LA VENDITA DI FARMACI VETERINARI (ART. 70 PUNTO 1)' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'ESERCIZIO DI VENDITA AL DETTAGLIO CHE EFFETTUA LA VENDITA DI FARMACI VETERINARI' and attivita ilike 'MEDIA STRUTTURA DI VENDITA CHE EFFETTUA LA VENDITA DI FARMACI VETERINARI (ART. 70 PUNTO 1)' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'FARMACI VETERINARI' and aggregazione ilike 'STRUTTURA VETERINARIA MUNITA DI SCORTA DI FARMACI VETERINARI' and attivita ilike 'STRUTTURA VETERINARIA MUNITA DI SCORTA DI FARMACI VETERINARI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'AMBULATORIO VETERINARIO' and attivita ilike 'PRIVATO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'A' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'AMBULATORIO VETERINARIO' and attivita ilike 'PUBBLICO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'ENTE O IMPRESA CHE UTILIZZA AMBULANZE VETERINARIE' and attivita ilike 'ENTE O IMPRESA CHE UTILIZZA AMBULANZE VETERINARIE' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'CLINICA VETERINARIA - CASA DI CURA VETERINARIA' and attivita ilike 'PRIVATO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'C' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'CLINICA VETERINARIA - CASA DI CURA VETERINARIA' and attivita ilike 'PUBBLICO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'L' , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'LABORATORIO VETERINARIO DI ANALISI' and attivita ilike 'LABORATORIO VETERINARIO DI ANALISI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'OSPEDALE VETERINARIO' and attivita ilike 'PRIVATO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'O' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'OSPEDALE VETERINARIO' and attivita ilike 'PUBBLICO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'S' , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'STUDIO VETERINARIO' and attivita ilike 'CON ACCESSO DI ANIMALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'S' , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'STRUTTURE VETERINARIE' and aggregazione ilike 'STUDIO VETERINARIO' and attivita ilike 'SENZA ACCESSO DI ANIMALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'CENTRO ADDESTRAMENTO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC03', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'ALLEVAMENTO DI ALTRI ANIMALI D''AFFEZIONE' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC03', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'ALLEVAMENTO CANI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC03', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'ALLEVAMENTO GATTI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC10', sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'AREA DEGENZA' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC07', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'PENSIONE' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC01', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'RIFUGIO-RICOVERO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC02', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'RIFUGIO SANITARIO' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CIMITERI PER ANIMALI DA COMPAGNIA' and attivita ilike 'CIMITERI PER ANIMALI DA COMPAGNIA' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI NON SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (I)' and attivita ilike 'ATTIVITA ASSISTITA (AAA) CON ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI NON SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (I)' and attivita ilike 'ATTIVITA ASSISTITA (AAA) SENZA ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI NON SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (I)' and attivita ilike 'EDUCAZIONE ASSISTITA (EAA) CON ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI NON SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (I)' and attivita ilike 'EDUCAZIONE ASSISTITA (EAA) SENZA ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI NON SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (I)' and attivita ilike 'TERAPIA ASSISTITA (TAA) CON ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI NON SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (I)' and attivita ilike 'TERAPIA ASSISTITA (TAA) SENZA ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'COMMERCIO AL DETTAGLIO ANIMALI D''AFFEZIONE' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'COMMERCIO ALL''INGROSSO ANIMALI D''AFFEZIONE IN LOCALI CON SUPERFICIE TOTALE LORDA COMPRENSIVA DI SERVIZI E DEPOSITI INFERIORE A 400 MQ' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CANILI/STRUTTURE DI DETENZIONE ANIMALI D''AFFEZIONE' and attivita ilike 'COMMERCIO ALL''INGROSSO ANIMALI D''AFFEZIONE IN LOCALI CON SUPERFICIE TOTALE LORDA COMPRENSIVA DI SERVIZI E DEPOSITI SUPERIORE A 400 MQ' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (IAA)' and attivita ilike 'ATTIVITA ASSISTITA (AAA) CON ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (IAA)' and attivita ilike 'ATTIVITA ASSISTITA (AAA) SENZA ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (IAA)' and attivita ilike 'EDUCAZIONE ASSISTITA (EAA) CON ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (IAA)' and attivita ilike 'EDUCAZIONE ASSISTITA (EAA) SENZA ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (IAA)' and attivita ilike 'TERAPIA ASSISTITA (TAA) CON ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'CENTRI SPECIALIZZATI PER INTERVENTI ASSISTITI CON GLI ANIMALI (IAA)' and attivita ilike 'TERAPIA ASSISTITA (TAA) SENZA ANIMALI RESIDENZIALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'MOSTRA, FIERA O EVENTO A CARATTERE TEMPORANEO CON PRESENZA DI ANIMALI' and attivita ilike 'MOSTRA, FIERA O EVENTO A CARATTERE TEMPORANEO CON PRESENZA DI ANIMALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = false, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'TOELETTATURA ANIMALI' and attivita ilike 'TOELETTATURA ANIMALI' and rev = 11) and rev = 11; 
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC17', sinac_codice_struttura_veterinaria = null , vam = false, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = (select id_nuova_linea_attivita from ml8_linee_attivita_nuove_materializzata where enabled and macroarea ilike 'IGIENE URBANA VETERINARIA' and aggregazione ilike 'ATTIVITA'' DI TOELETTATURA ITINERANTE' and attivita ilike 'ATTIVITA'' DI TOELETTATURA ITINERANTE' and rev = 11) and rev = 11; 


--ML10 e 8
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC02', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 59; --IGIENE URBANA VETERINARIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC02', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 4; --IGIENE URBANA VETERINARIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC02', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 54; --IGIENE URBANA VETERINARIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC02', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 20009; --IGIENE URBANA VETERINARIA->CANILE/PENSIONE PER ANIMALI DA COMPAGNIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC02', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 40017; --IGIENE URBANA VETERINARIA->CANILE/PENSIONE PER ANIMALI DA COMPAGNIA->CANILE/PENSIONE PER ANIMALI DA COMPAGNIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC02', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 20219; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (canile)"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC03', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 40556; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (canile)->ALLEVAMENTO CANI "
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC03', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 40555; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (canile)->ALLEVAMENTO GATTI"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC07', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 40563; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (canile)->PENSIONE"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC01', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 40561; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (canile)->RIFUGIO-RICOVERO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC02', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = true, bdu_operatore_commerciale = false where trashed is null and id_linea = 40562; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (canile)->RIFUGIO SANITARIO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 20221; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (commercio dettaglio)"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 40558; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (commercio dettaglio)->COMMERCIO AL DETTAGLIO ANIMALI D'AFFEZIONE"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 20222; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (commercio ingrosso)"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 40559; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (commercio ingrosso)->COMMERCIO ALL'INGROSSO ANIMALI D'AFFEZIONE IN LOCALI CON SUPERFICIE TOTALE LORDA COMPRENSIVA DI SERVIZI E DEPOSITI INFERIORE A 400 MQ"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 40560; --IGIENE URBANA VETERINARIA->CANILI/STRUTTURE DI DETENZIONE ANIMALI D'AFFEZIONE (commercio ingrosso)->COMMERCIO ALL'INGROSSO ANIMALI D'AFFEZIONE IN LOCALI CON SUPERFICIE TOTALE LORDA COMPRENSIVA DI SERVIZI E DEPOSITI SUPERIORE A 400 MQ"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 20012; --IGIENE URBANA VETERINARIA->COMMERCIO AL DETTAGLIO DI ANIMALI DA COMPAGNIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 40026; --IGIENE URBANA VETERINARIA->COMMERCIO AL DETTAGLIO DI ANIMALI DA COMPAGNIA->VENDITA AL DETTAGLIO ANIMALI DA COMPAGNIA_CON VENDITA DI CANI E/O GATTI E/O FURETTI"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 20013; --IGIENE URBANA VETERINARIA->COMMERCIO ALL'INGROSSO  DI ANIMALI DA COMPAGNIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = 'TC06', sinac_codice_struttura_veterinaria = null , vam = false, bdu = true, bdu_canile = false, bdu_operatore_commerciale = true where trashed is null and id_linea = 40028; --IGIENE URBANA VETERINARIA->COMMERCIO ALL'INGROSSO  DI ANIMALI DA COMPAGNIA->VENDITA ALL'INGROSSO ANIMALI DA COMPAGNIA_CON VENDITA DI CANI E/O GATTI E/O FURETTI"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'A' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 7; --STRUTTURE VETERINARIE"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'A' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 84; --STRUTTURE VETERINARIE"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'A' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 20291; --STRUTTURE VETERINARIE->AMBULATORIO VETERINARIO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'A' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 20025; --STRUTTURE VETERINARIE->AMBULATORIO VETERINARIO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'A' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 40051; --STRUTTURE VETERINARIE->AMBULATORIO VETERINARIO->PUBBLICO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'A' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 40774; --STRUTTURE VETERINARIE->AMBULATORIO VETERINARIO->PUBBLICO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'C' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 20292; --STRUTTURE VETERINARIE->CLINICA VETERINARIA - CASA DI CURA VETERINARIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'C' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 20027; --STRUTTURE VETERINARIE->CLINICA VETERINARIA - CASA DI CURA VETERINARIA"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'C' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 40055; --STRUTTURE VETERINARIE->CLINICA VETERINARIA - CASA DI CURA VETERINARIA->PUBBLICO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'C' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 40776; --STRUTTURE VETERINARIE->CLINICA VETERINARIA - CASA DI CURA VETERINARIA->PUBBLICO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'O' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 20295; --STRUTTURE VETERINARIE->OSPEDALE VETERINARIO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'O' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 20029; --STRUTTURE VETERINARIE->OSPEDALE VETERINARIO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'O' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 40058; --STRUTTURE VETERINARIE->OSPEDALE VETERINARIO->PUBBLICO"
update master_list_flag_linee_attivita set sinac = true, sinac_codice_struttura_detenzione = null, sinac_codice_struttura_veterinaria = 'O' , vam = true, bdu = false, bdu_canile = false, bdu_operatore_commerciale = false where trashed is null and id_linea = 40780; --STRUTTURE VETERINARIE->OSPEDALE VETERINARIO->PUBBLICO"

