package it.us.web.bean.vam.lookup;

import it.us.web.bean.vam.Ecg;
import it.us.web.bean.vam.EcoAddomeEsito;

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Proxy;
import org.hibernate.annotations.Where;


/**
 * LookupAritmie generated by hbm2java
 */
@Entity
@Table(name = "lookup_aritmie")
public class LookupAritmie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String nome;
	private Set<Ecg> ecgs;

	public LookupAritmie(){}
	
	
	public LookupAritmie(int id,String nome) {
		this.id = id;
	}

	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 64)	
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "aritmie")
	public Set<Ecg> getEcgs() {
		return ecgs;
	}

	public void setEcgs(Set<Ecg> ecgs) {
		this.ecgs = ecgs;
	}
	
	@Override
	public String toString()
	{
		return nome;
	}
	
	@Transient
	public String getNomeEsame()
	{
		return "Aritmia";
	}

}
