-- CHI: Bartolo Sansone	
-- COSA: Stampa scheda targa
-- QUANDO: 12/02/2018

insert into lookup_tipo_scheda_operatore (code, description, titolo, firma_data, nome_file) values (41, 'Anagrafica Stabilimenti - Scheda Informazione Specifica', 'Scheda Impresa', false, 'SchedaAnagraficaSpecifica');

update scheda_operatore_metadati set enabled = false where tipo_operatore = 41;insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','DATI IMPRESA','capitolo','','','','A','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','TIPO IMPRESA','','distinct(tipo_impresa)','opu_operatori_denormalizzati_view','id_stabilimento =#stabid#','AA','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','TIPO SOC./COOP.','','distinct(tipo_societa)','opu_operatori_denormalizzati_view','id_stabilimento =#stabid#','AAA','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','NOME/DITTA/RAGIONE SOCIALE/DENOMINAZIONE SOCIALE','','distinct ragione_sociale ','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','AAAA','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','PARTITA IVA','','distinct partita_iva ','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','B','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','NOTE','','distinct(note_operatore)','opu_operatori_denormalizzati_view','id_stabilimento =#stabid#','CC','screen');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','ASL','asl','distinct stab_asl','opu_operatori_denormalizzati_view','id_stabilimento =#stabid#','CCC','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','NUMERO REGISTRAZIONE GISA ','barcode','distinct numero_registrazione ','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','CCCC','print');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','INFORMAZIONE','','f.label_campo || '': '' || COALESCE(tipomobili.description, v.valore_campo, '''') 
','linee_mobili_html_fields f join linee_mobili_fields_value v on f.id = v.id_linee_mobili_html_fields 
left join lookup_tipo_mobili tipomobili on tipomobili.code::text = v.valore_campo and f.tabella_lookup = ''lookup_tipo_mobili''','id_rel_stab_linea = (select id_rel_stab_linea from linee_mobili_fields_value where id = #idcampoesteso#) and indice = (select indice from linee_mobili_fields_value where id = #idcampoesteso#)','GGGG','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','PROSSIMO CONTROLLO CON LA TECNICA DELLA SORVEGLIANZA','','case when data_prossimo_controllo is null then '''' else to_char(data_prossimo_controllo, ''dd/mm/yyyy'') end as prossimo_controllo ','opu_stabilimento','opu_stabilimento.id=#stabid#','F','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','NOTE STABILIMENTO','','distinct(note_stabilimento)','opu_operatori_denormalizzati_view','id_stabilimento =#stabid#','FF','screen');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','LISTA LINEE PRODUTTIVE','capitolo','','','','G','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','ATTIVITA','','norme.description  
|| case when linea_codice_nazionale <> '''' then ''<br><b>Approval Number / CUN:</b> '' || linea_codice_nazionale || ''<br/>'' else '''' end 
,
string_agg(
case when linea_numero_registrazione <> '''' then ''<b>Num. Reg.:</b> '' || linea_numero_registrazione else ''NUMERO MANCANTE'' end || ''<br/>'' 

|| case when linea_codice_ufficiale_esistente <> '''' then ''<i>Gia  codificato come:</i> '' || linea_codice_ufficiale_esistente || ''<br/>'' else '''' end 
|| case when path_attivita_completo <> '''' then replace(path_attivita_completo, ''->'', ''<br/>->'')  else '''' end || ''<br/>''
|| case when pregresso_o_import =true then ''<b>Data Inizio:</b> ''||to_char(data_inizio, ''dd/mm/yyyy'')

when linea_modified is not null then ''<b>Data validazione:</b> '' ||to_char(linea_modified, ''dd/mm/yyyy'') || '' <i>(NOTA BENE: La data di inizio attività corrisponde alla data di presentazione SCIA, riportata sulla ricevuta rilasciata dal SUAP)</i>''  ||''; '' else '''' end 
 || case when data_fine is not null then '' <b>Data fine:</b> '' ||to_char(data_fine, ''dd/mm/yyyy'') else '''' end ||  ''<br/> <b>Stato:</b> '' || linea_stato_text 
 ,''<br><hr>'')','opu_operatori_denormalizzati_view 
 join opu_lookup_norme_master_list norme on norme.code = id_norma','id_stabilimento =#stabid#  
 group by   norme.description  
|| case when linea_codice_nazionale <> '''' then ''<br><b>Approval Number / CUN:</b> '' || linea_codice_nazionale || ''<br/>'' else '''' end ','GG','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','CODICE FISCALE','','distinct codice_fiscale_impresa ','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','BB','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','RAPPRESENTANTE LEGALE','','distinct nome_rapp_sede_legale || '' '' || cognome_rapp_sede_legale || '' '' || cf_rapp_sede_legale ||''<br/>''
|| '''' ||''Residente in:'' ||'' ''|| coalesce (indirizzo_rapp_sede_legale, '' '')','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','BBB','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','INDIRIZZO SEDE LEGALE','','distinct(
case when impresa_id_tipo_impresa = 1 then '''' 
else 
case when indirizzo_sede_legale is not null then indirizzo_sede_legale else '''' end  || '', '' || 
case when cap_sede_legale is not null then cap_sede_legale else '''' end  || '' '' || case when comune_sede_legale is not null then 
comune_sede_legale else '''' end  || '', '' || case when prov_sede_legale is not null then prov_sede_legale  else '''' end end
)','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','BBBB','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','INDIRIZZO STABILIMENTO','','distinct(
case when stab_id_attivita=2 then '''' else
 case when indirizzo_stab is not null then indirizzo_stab || '','' || civico_sede_stab else '''' end || '', '' || 
case when cap_stab is not null then cap_stab else '''' end || '' '' || case when comune_stab  is not null then comune_stab else '''' end || '', '' ||
case when prov_stab is not null then prov_stab else '''' end ||'', Latitudine: '' || case when lat_stab is not null then lat_stab else 0  end
 ||'', Longitudine: '' ||case when  long_stab is not null then long_stab else  0 end end )','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','C','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','NUMERO REGISTRAZIONE GISA','','distinct numero_registrazione ','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','D','screen');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','GIA'' CODIFICATO COME:','','distinct (case when stab_codice_ufficiale_esistente is not null then  stab_codice_ufficiale_esistente else '''' end )
','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','DD','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','STATO','','distinct(case when id_stato = 0 then ''Registrato'' else stato end)','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','DDD','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','DATA CESSAZIONE','','distinct( case when id_stato <> 4 then '''' 
else to_char(data_fine, ''dd/mm/yyyy'')  end )','opu_operatori_denormalizzati_view','id_stabilimento =#stabid#','DDDD','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','TIPO ATTIVITA'' ','','distinct(stab_descrizione_attivita)','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','E','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','CARATTERE','','distinct(stab_descrizione_carattere)','opu_operatori_denormalizzati_view ','id_stabilimento =#stabid#','EE','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','DATA INIZIO ATTIVITA''','','distinct(case when 
data_inizio_attivita is not null
then to_char(data_inizio_attivita, ''dd/mm/yyyy'')  else '''' end)
','opu_operatori_denormalizzati_view','id_stabilimento =#stabid#','EEE','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','DATA FINE ATTIVITA''','','distinct(case when stab_id_carattere = 2 then to_char(data_fine_attivita, ''dd/mm/yyyy'')  else '''' end)
','opu_operatori_denormalizzati_view','id_stabilimento =#stabid#','EEEE','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('41','INFORMAZIONE SPECIFICA','capitolo','','','','GGG','');

