package it.izs.bdn.anagrafica.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApistoproEndpoint", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApistoproEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.InsertPersoneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertApistoproResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApistoproEndpoint/insertApistoproRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApistoproEndpoint/insertApistoproResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApistoproEndpoint/insertApistopro/Fault/BusinessWsException")
    })
    public InsertApistoproResponse insertStoricoProprietario(
        @WebParam(name = "insertStoricoProprietario", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        InsertApistopro parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    

}
