
package it.izs.bdn.anagrafica.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AziendaEndpointService", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", wsdlLocation = "https://ws.izs.it:80/j6_bdn/ws/anagrafica/azienda?WSDL")
public class AziendaEndpointService
    extends Service
{

    private final static URL AZIENDAENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException AZIENDAENDPOINTSERVICE_EXCEPTION;
    private final static QName AZIENDAENDPOINTSERVICE_QNAME = new QName("http://ws.anagrafica.bdn.izs.it/", "AziendaEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ws.izs.it:80/j6_bdn/ws/anagrafica/azienda?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AZIENDAENDPOINTSERVICE_WSDL_LOCATION = url;
        AZIENDAENDPOINTSERVICE_EXCEPTION = e;
    }

    public AziendaEndpointService() {
        super(__getWsdlLocation(), AZIENDAENDPOINTSERVICE_QNAME);
    }

    public AziendaEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AZIENDAENDPOINTSERVICE_QNAME, features);
    }

    public AziendaEndpointService(URL wsdlLocation) {
        super(wsdlLocation, AZIENDAENDPOINTSERVICE_QNAME);
    }

    public AziendaEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AZIENDAENDPOINTSERVICE_QNAME, features);
    }

    public AziendaEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AziendaEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AziendaEndpoint
     */
    @WebEndpoint(name = "AziendaEndpointPort")
    public AziendaEndpoint getAziendaEndpointPort() {
        return super.getPort(new QName("http://ws.anagrafica.bdn.izs.it/", "AziendaEndpointPort"), AziendaEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AziendaEndpoint
     */
    @WebEndpoint(name = "AziendaEndpointPort")
    public AziendaEndpoint getAziendaEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.anagrafica.bdn.izs.it/", "AziendaEndpointPort"), AziendaEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AZIENDAENDPOINTSERVICE_EXCEPTION!= null) {
            throw AZIENDAENDPOINTSERVICE_EXCEPTION;
        }
        return AZIENDAENDPOINTSERVICE_WSDL_LOCATION;
    }

}
