
package it.izs.bdn.anagrafica.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersoneEndpoint", targetNamespace = "http://ws.anagrafica.bdn.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersoneEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.InsertPersoneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertPersoneResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/insertPersoneRequest", output = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/insertPersoneResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/insertPersone/Fault/BusinessWsException")
    })
    public InsertPersoneResponse insertPersone(
        @WebParam(name = "insertPersone", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        InsertPersone parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.SearchPersoneByPkResponse
     */
    @WebMethod
    @WebResult(name = "searchPersoneByPkResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/searchPersoneByPkRequest", output = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/searchPersoneByPkResponse")
    public SearchPersoneByPkResponse searchPersoneByPk(
        @WebParam(name = "searchPersoneByPk", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        SearchPersoneByPk parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.UpdatePersoneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updatePersoneResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/updatePersoneRequest", output = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/updatePersoneResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/updatePersone/Fault/BusinessWsException")
    })
    public UpdatePersoneResponse updatePersone(
        @WebParam(name = "updatePersone", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        UpdatePersone parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.DeletePersoneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deletePersoneResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/deletePersoneRequest", output = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/deletePersoneResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/deletePersone/Fault/BusinessWsException")
    })
    public DeletePersoneResponse deletePersone(
        @WebParam(name = "deletePersone", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        DeletePersone parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.SearchPersoneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchPersoneResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/searchPersoneRequest", output = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/searchPersoneResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/PersoneEndpoint/searchPersone/Fault/BusinessWsException")
    })
    public SearchPersoneResponse searchPersone(
        @WebParam(name = "searchPersone", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        SearchPersone parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

}
