
package it.izs.bdn.anagrafica.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UniproEndpoint", targetNamespace = "http://ws.anagrafica.bdn.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UniproEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.InsertUnitaProduttivaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertUnitaProduttivaResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertUnitaProduttivaRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertUnitaProduttivaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertUnitaProduttiva/Fault/BusinessWsException")
    })
    public InsertUnitaProduttivaResponse insertUnitaProduttiva(
        @WebParam(name = "insertUnitaProduttiva", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        InsertUnitaProduttiva parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.InsertAllevfamTOavidetattResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertAllevfamTOavidetattResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertAllevfamTOavidetattRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertAllevfamTOavidetattResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertAllevfamTOavidetatt/Fault/BusinessWsException")
    })
    public InsertAllevfamTOavidetattResponse insertAllevfamTOavidetatt(
        @WebParam(name = "insertAllevfamTOavidetatt", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        InsertAllevfamTOavidetatt parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.UpdateUnitaproduttivaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateUnitaproduttivaResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/updateUnitaproduttivaRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/updateUnitaproduttivaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/updateUnitaproduttiva/Fault/BusinessWsException")
    })
    public UpdateUnitaproduttivaResponse updateUnitaproduttiva(
        @WebParam(name = "updateUnitaproduttiva", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        UpdateUnitaproduttiva parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.SearchDettaglioAttivitaByPKResponse
     */
    @WebMethod
    @WebResult(name = "searchDettaglioAttivitaByPKResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchDettaglioAttivitaByPKRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchDettaglioAttivitaByPKResponse")
    public SearchDettaglioAttivitaByPKResponse searchDettaglioAttivitaByPK(
        @WebParam(name = "searchDettaglioAttivitaByPK", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        SearchDettaglioAttivitaByPK parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.SearchUnitaProduttivaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchUnitaProduttivaResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchUnitaProduttivaRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchUnitaProduttivaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchUnitaProduttiva/Fault/BusinessWsException")
    })
    public SearchUnitaProduttivaResponse searchUnitaProduttiva(
        @WebParam(name = "searchUnitaProduttiva", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        SearchUnitaProduttiva parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.SearchUnitaProduttivaByPKResponse
     */
    @WebMethod
    @WebResult(name = "searchUnitaProduttivaByPKResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchUnitaProduttivaByPKRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchUnitaProduttivaByPKResponse")
    public SearchUnitaProduttivaByPKResponse searchUnitaProduttivaByPK(
        @WebParam(name = "searchUnitaProduttivaByPK", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        SearchUnitaProduttivaByPK parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.InsertDettaglioAttivitaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertDettaglioAttivitaResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertDettaglioAttivitaRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertDettaglioAttivitaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/insertDettaglioAttivita/Fault/BusinessWsException")
    })
    public InsertDettaglioAttivitaResponse insertDettaglioAttivita(
        @WebParam(name = "insertDettaglioAttivita", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        InsertDettaglioAttivita parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.UpdateDettaglioAttivitaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateDettaglioAttivitaResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/updateDettaglioAttivitaRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/updateDettaglioAttivitaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/updateDettaglioAttivita/Fault/BusinessWsException")
    })
    public UpdateDettaglioAttivitaResponse updateDettaglioAttivita(
        @WebParam(name = "updateDettaglioAttivita", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        UpdateDettaglioAttivita parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.DeleteDettaglioAttivitaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteDettaglioAttivitaResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/deleteDettaglioAttivitaRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/deleteDettaglioAttivitaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/deleteDettaglioAttivita/Fault/BusinessWsException")
    })
    public DeleteDettaglioAttivitaResponse deleteDettaglioAttivita(
        @WebParam(name = "deleteDettaglioAttivita", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        DeleteDettaglioAttivita parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.SearchDettaglioAttivitaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchDettaglioAttivitaResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchDettaglioAttivitaRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchDettaglioAttivitaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchDettaglioAttivita/Fault/BusinessWsException")
    })
    public SearchDettaglioAttivitaResponse searchDettaglioAttivita(
        @WebParam(name = "searchDettaglioAttivita", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        SearchDettaglioAttivita parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.bdn.anagrafica.ws.SearchDettaglioAttivitaByAziendaCodiceResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchDettaglioAttivitaByAziendaCodiceResponse", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "result")
    @Action(input = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchDettaglioAttivitaByAziendaCodiceRequest", output = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchDettaglioAttivitaByAziendaCodiceResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.anagrafica.bdn.izs.it/UniproEndpoint/searchDettaglioAttivitaByAziendaCodice/Fault/BusinessWsException")
    })
    public SearchDettaglioAttivitaByAziendaCodiceResponse searchDettaglioAttivitaByAziendaCodice(
        @WebParam(name = "searchDettaglioAttivitaByAziendaCodice", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", partName = "parameters")
        SearchDettaglioAttivitaByAziendaCodice parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

}
