CREATE TABLE camera_commercio
(
	
	 id serial primary key,
	 data_importazione_osa Timestamp,
	 data_import Timestamp,
		provincia_cciaa          varchar(320)	,
		num_iscrizione           varchar(320)	,
		progressivo_ul           varchar(320)	,
		cf_impresa               varchar(320)	,
		num_registro_imprese     varchar(320)	,
	data_iscrizione_posiz_rea                 Timestamp	,
	data_caricamento_archivio_pos_rea         Timestamp	,
	provincia_sede_legale                   varchar(320)	,
	codice_stato_sede_legale                varchar(320)	,
	codice_istat_comune_sede_legale         varchar(320)	,
	descrizione_comune_sede_legale          varchar(320)	,
	descrizione_localita_sede_legale        varchar(320)	,
	cod_toponimo_sede_legale                varchar(320)	,
	via_sede_legale                         varchar(320)	,
	civico_sede_legale                      varchar(320)	,
	cap_sede_legale                         varchar(320)	,
	cod_stradario_sede_legale               varchar(320)	,
	data_iscrizione_registro_imprese        varchar(320)  ,
		cod_sez_spec_1  varchar(320)	,
	data_inizio_appartenenza_sez_spec_1     Timestamp	,
	flag_coltiv_diretto_1                   boolean		,
	data_fine_appartenenza_sez_spec_1       Timestamp	,
		cod_sez_spec_2  varchar(320)	,
	data_inizio_appartenenza_sez_spec_2     Timestamp	,
	flag_coltiv_diretto_2                   boolean		,
	data_fine_appartenenza_sez_spec_2       Timestamp	,
		cod_sez_spec_3      varchar(320)	,
	data_inizio_appartenenza_sez_spec_3        Timestamp	,
	flag_coltiv_diretto_3                      boolean		,
		data_fine_appartenenza_sez_spec_3        Timestamp  ,
	ragione_sociale               varchar(320)	,
		partita_iva                   varchar(320)	,
		cod_natura_giuridica          varchar(320)	,
		stato_attivita_impresa        varchar(320)	,
		capitale_sociale              varchar(320)	,
		valuta_capitale_sociale       varchar(320)	,
		oggetto_sociale_1             varchar(320)	,
		oggetto_sociale_2             varchar(320)	,
		oggetto_sociale_3             varchar(320)	,
		oggetto_sociale_4             varchar(320)	,
		flag_omissis_oggetto_sociale     boolean	,
	cod_tipo_liquidazione         varchar(320)		,
	 data_apertura_liquidazione      Timestamp	,
		cod_tipo_ul               varchar(320)	,
		tipo_localizzazione       varchar(320)	,
		denominazione_ul          varchar(320)	,
		insegna_ul                varchar(320)	,
	data_apertura_ul              Timestamp	,
	codice_stato_ul                varchar(320) ,
	provincia_ul                   varchar(320) ,
	codice_istat_ul                varchar(320) ,
	descrizione_comune_ul          varchar(320) ,
	descrizione_localita_ul        varchar(320) ,
	cod_toponimo_ul                varchar(320) ,
	via_ul                         varchar(320) ,
	civico_ul                      varchar(320) ,
	cap_ul                         varchar(320) ,
	cod_stradario_ul               varchar(320) ,
			telefono_ul                           varchar(320),
			stato_attivita_ul                     varchar(320),
			cod_acusale_cessazione_ul             varchar(320),
	  data_cessazione_ul                      Timestamp	  ,
	  data_denuncia_cessazione_ul             Timestamp   ,
			anno_denuncia_addetti_ul              varchar(320),
			num_addetti_familiari_ul              varchar(320),
			num_addetti_subordinati_ul            varchar(320),
			cod_attivita_istat_91_primario        varchar(320),
	descrizione_attivita_ul_1                        varchar(320)	,
	descrizione_attivita_ul_2                        varchar(320)	,
	descrizione_attivita_ul_3                        varchar(320)	,
	descrizione_attivita_ul_4                        varchar(320)	,
	flag_omissis_descrizione_attivita_ul             boolean	    ,
	 cod_tipo_ruolo_1                                varchar(320) ,
  		cod_forma_ruolo_1                            varchar(320) ,
		num_ruolo_1                                    varchar(320)	,
		data_inizio_ruolo_1                            Timestamp    ,
		data_cessazione_ruolo_1                        Timestamp    ,
			cod_tipo_ruolo_2                             varchar(320) ,
		cod_forma_ruolo_2                              varchar(320)	,
		num_ruolo_2                                    varchar(320)	,
	 data_inizio_ruolo_2                             Timestamp	  ,
	  data_cessazione_ruolo_2                        Timestamp	  ,
  	cod_tipo_ruolo_3                               varchar(320)	,
		cod_forma_ruolo_3                              varchar(320)	,
		num_ruolo_3                                    varchar(320)	,
	 data_inizio_ruolo_3                             Timestamp	  ,
	 data_cessazione_ruolo_3                         Timestamp	  ,
  	cod_tipo_ruolo_4                               varchar(320)	,
		cod_forma_ruolo_4                              varchar(320)	,
		num_ruolo_4                                    varchar(320)	,
	  data_inizio_ruolo_4                            Timestamp	  ,
		data_cessazione_ruolo_4                        Timestamp    ,
 	cod_tipo_ruolo_5                               varchar(320)	,
		cod_forma_ruolo_5                              varchar(320)	,
		num_ruolo_5                                    varchar(320)	,
	  data_inizio_ruolo_5                            Timestamp	  ,
	  data_cessazione_ruolo_5                        Timestamp 	  ,
	 flag_omissis_albi_ruoli       boolean
);
