CREATE TABLE farmacie
(
  id_farmacia integer NOT NULL DEFAULT nextval(('farmacia_id_seq'::text)::regclass),
  ragione_sociale character varying(50),
  stato character varying(80),
  data_cambio_stato timestamp(3) without time zone,
  site_id integer,
  indirizzo character varying(80),
  citta character varying(80),
  provincia character varying(80),
  latitude double precision DEFAULT 0,
  longitude double precision DEFAULT 0,
  num_ric_ingrosso character varying(12),
  data_ric_ingrosso timestamp(3) without time zone,
  num_ric_dettaglio text,
  data_ric_dettaglio timestamp(3) without time zone,
  entered timestamp(3) without time zone NOT NULL DEFAULT now(),
  enteredby integer NOT NULL,
  modified timestamp(3) without time zone NOT NULL DEFAULT now(),
  modifiedby integer NOT NULL,
  trashed_date timestamp(3) without time zone,
  id_prescrizione integer,
  pregresso boolean,   
  note1 text,
  data_verifica_annua timestamp without time zone
)
WITH (OIDS=FALSE);
ALTER TABLE farmacie OWNER TO postgres;
--
-- PostgreSQL database dump
--

-- Started on 2010-11-11 10:17:58

SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

SET search_path = public, pg_catalog;

--
-- TOC entry 6021 (class 0 OID 1142729)
-- Dependencies: 5632
-- Data for Name: farmacie; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Capozza Claudia                            ',   'attivo',        NULL,1 ,'Via S.Rocco                                               ','Avellino                               ','AV',0.0,0.0,'15/C.112/g ','1993-04-29','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Ce.Di.Far.Me.Coop arl                      ',   'attivo',        NULL,1 ,'Via Fontana Angelica,1                                    ','Ariano Irpino                          ','AV',0.0,0.0,'15/C.104/g ','1993-08-09','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'NPFARMA                                    ', 'revocato','2006-10-05',1 ,'Via Bellini, 26/28                                        ','Grottaminarda                          ','AV',0.0,0.0,'15/N,23/g  ',NULL        ,'          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'NPFARMA                                    ', 'revocato','2006-10-05',1 ,'Via Bellini, 26/28                                        ','Grottaminarda                          ','AV',0.0,0.0,'           ',NULL        ,'15/V.20/v ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'SANNIOVET                                  ', 'revovato','2009-08-05',1 ,'Via Nazionale                                             ','                                       ','AV',0.0,0.0,'15/S.34/g  ',NULL        ,'          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'SANNIOVET                                  ', 'revocato',        NULL,1 ,'Via Nazionale                                             ','                                       ','AV',0.0,0.0,'           ',NULL        ,'15/S.22/v ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'So. Farma.Morra                            ', '        ',        NULL,2 ,'Via Capozzi,22/24                                         ','Avellino                               ','AV',0.0,0.0,'15/S.5/g   ','2002-04-22','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'La Veterinaria srl                         ', '        ',        NULL,2 ,'Via Appia, 87                                             ','Atripalda                              ','AV',0.0,0.0,'15/V.36/g  ','2009-12-02','15/V.24/v ','2009-12-02','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Soc.D.ri Sabato & C.Farmaceutici srl       ', '        ',        NULL,2 ,'                                                          ','                                       ','  ',0.0,0.0,'15/S.10/g  ','1993-05-07','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Dott.Ragucci Massimo                       ', '        ',        NULL,3 ,'Via Piano dello Stallone snc                              ','S.Giorgio la Molara                    ','BN',0.0,0.0,'15/R.26/g  ','1998-07-22','15/R.26/v ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Federico Manna srl                         ', '        ',        NULL,3 ,'Via S.Gaspare del Bufalo 1/5/7                            ','Benevento                              ','BN',0.0,0.0,'15/M.12/g  ','1994-10-20','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Svima farmaceutici srl                     ', 'sospeso ',        NULL,3 ,'C.da Panomorra                                            ','Benevento                              ','BN',0.0,0.0,'15/S.14/g  ','1995-05-15','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Unifarma soc. coop arl                     ', '        ',        NULL,3 ,'Via Corte Nocera snc                                      ','S.Salvatore Telesino                   ','BN',0.0,0.0,'15/U.29/g  ','1995-05-15','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Farmacia Veterinaria                       ', '        ',        NULL,3 ,'Contrada Cuffaro                                          ','Morcone                                ','BN',0.0,0.0,'15/F.30/g  ','2007-03-16','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'VITALZOO                                   ', 'revocato','2007-02-28',3 ,'Via Roma, 32                                              ','Morcone                                ','BN',0.0,0.0,'15/V.29/g  ',NULL       ,'           ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'VITALZOO                                   ', 'revocato','2007-02-28',3 ,'Via Roma, 32                                              ','Morcone                                ','BN',0.0,0.0,'           ',NULL       ,'15/S15.V   ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Euroveterinaria srl                        ', '        ',NULL        ,4 ,'Via S.Ferdinando 1                                        ','Alvignano                              ','CE',0.0,0.0,'15/E21/G   ','2001-12-17','15/E.21v  ','2001-12-21','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Profarmaco                                 ', '        ',NULL        ,4 ,'Via Bologna,22                                            ','Casagiove                              ','CE',0.0,0.0,'15/P.2/g   ','2002-01-02','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Biofarma srl                               ', '        ',NULL        ,4 ,'Via Pontone                                               ','localita' Puccianiello Caserta          ','CE',0.0,0.0,'15/B.4/G   ','1993-07-13','15/B.4/v  ','1993-07-13','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Galenitalia                                ', 'revocato',NULL        ,4 ,'Via Passionisti,15                                        ','Casagiove                              ','CE',0.0,0.0,'15/G.37//g ','1999-07-15','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Dell''Aquila Veterinaria                   ', '        ',NULL        ,4 ,'Via Patturelli 16/18                                      ','Caserta                                ','CE',0.0,0.0,'15/D.13/g  ','1994-07-28','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'EMX2 Srl                                   ', '        ',NULL        ,4 ,'Via Gramsci 100                                           ','S.Felice a Cancello                    ','CE',0.0,0.0,'15/E.22/g  ','1999-12-02','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'AGRIZOO FARM                               ', '        ',NULL        ,4 ,'Via veneto, 39                                            ','Marcianise                             ','CE',0.0,0.0,'15/A.66/g  ','1993-03-24','15/A.66/v ','1994-01-04','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Neifarma L. spa                            ', '        ',NULL        ,4 ,'Via pasionisti 15                                         ','Casagiove                              ','CE',0.0,0.0,'15/N.7/g   ','1995-03-01','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Italia Vet                                 ', '        ',NULL        ,4 ,'Via S.S.Riardo                                            ','Caserta                                ','CE',0.0,0.0,'15/I.18/g  ','2005-12-22','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'VETZOO                                     ', 'revocato',NULL        ,4 ,'Via Provinciale Riardo                                    ','Petramelara Riardo                     ','CE',0.0,0.0,'15/V.32/g  ','2008-02-22','15/v.21/v ','2008-04-02','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Farmavetersud                              ', '        ',NULL        ,4 ,'Piazza Roma, 4                                            ','Capriati a Volturno                    ','CE',0.0,0.0,'15/V.37/g  ','2010-05-04','15/V.25/v ','2010-05-12','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), '                                           ', '        ',NULL        ,4 ,'                                                          ','                                       ','  ',0.0,0.0,'           ',NULL        ,'          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'CIB FARM                                   ', '        ',NULL        ,4 ,'Via SS 158 dir Sud,31                                     ','Piedimonte Matese                      ','CE',0.0,0.0,'15/C.35/g  ',NULL        ,'          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'CIB FARM                                   ', '        ',NULL        ,4 ,'Via SS 158 dir Sud,31                                     ','Piedimonte Matese                      ','CE',0.0,0.0,'           ',NULL        ,'15/C.33/v ','2009-10-16','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'SO.FARMA.MORRA SPA                         ', '        ',NULL        ,5 ,'Via Nazionale Appia 86                                    ','Curti                                  ','CE',0.0,0.0,'157S.3/g   ','1993-04-24','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Farmavet srl                               ', '        ',NULL        ,5 ,'Via Cupa,2                                                ','Grazzanise                             ','CE',0.0,0.0,'15/F.146/g ','1999-05-24','15/F.146/v',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'ZOOVET srl                                 ', '        ',NULL        ,5 ,'Via Roma per Cappella Reale, 79                           ','Cancello Arnone                        ','CE',0.0,0.0,'15/Z.54/g  ',NULL        ,'15/Z.54/v ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'VET FARM S.R.L.                            ', '        ',NULL        ,5 ,'Via Roma, 251                                             ','Cancello ed Arnone                     ','  ',0.0,0.0,'           ','2005-04-20','15/V 16/v ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'VETERFARM                                  ', '        ',NULL        ,5 ,'Via Nazionale Appia km200                                 ','Capua                                  ','CE',0.0,0.0,'15/V.12/g  ',NULL        ,'15/V.12/V ','2006-06-07','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Comifar distributore SPA                   ', '        ',NULL        ,5 ,'Via Consortile zona industriale                           ','Carinaro                               ','CE',0.0,0.0,'15/C.25/g  ',NULL        ,'          ',NULL       ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Valle dell''Orso Green Point Mixer 2000 srl', '        ',NULL        ,6 ,'Via Ferrante Imparato 192                                 ','Napoli                                 ','NA',0.0,0.0,'15/V.67/g  ','1994-10-20','15/V.67/v ','1995-01-11','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'EQUIVET SUD                                ', '        ',NULL        ,6 ,'Via R. Ruggiero 14/bis                                    ','Napoli                                 ','NA',0.0,0.0,'15/E.6/g   ','1993-03-16','15/E.6/V  ','1994-02-14','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Galenitalia SPA                            ', '        ',NULL        ,6 ,'Via Luigi Volpicella,32                                   ','Napoli                                 ','NA',0.0,0.0,'15/G.39/g  ','1999-07-15','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Diemmeci srl                               ', '        ',NULL        ,6 ,'Via G.Quagliariello,27                                    ','Napoli                                 ','NA',0.0,0.0,'15/D.16/g  ','1994-02-22','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Dal Re G.B.                                ', '        ',NULL        ,6 ,'Via Manzoni 26/a                                          ','Napoli                                 ','NA',0.0,0.0,'15/D.19/g  ','1993-05-07','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'For-Vet di Acerbo Anna                     ', '        ',NULL        ,6 ,'Via Raffaele Ruggero18/c                                  ','Agnani di Napoli                       ','NA',0.0,0.0,'15/F.77/g  ','1993-03-16','157F.77/v ','1994-04-05','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'SO.FARMA.MORRA SPA                         ', '        ',NULL        ,6 ,'Via provinciale delle Brecce,51                           ','Napoli                                 ','NA',0.0,0.0,'15/S.33/g  ','1993-05-20','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Farmaceutici Aristide Tonacci srl          ', '        ',NULL        ,7 ,'Circonv.Esterna 41/43                                     ','Mugnano di Napoli                      ','NA',0.0,0.0,'15/F.124/g ','1998-03-02','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Futura srl                                 ', '        ',NULL        ,7 ,'Via S. Nollo 62/64                                        ','Giugliano                              ','NA',0.0,0.0,'15/F.78/g  ','1999-07-30','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Logistica Farmaceutica                     ', '        ',NULL        ,7 ,'Strada Prov. Pianura                                      ','Pozzuoli                               ','NA',0.0,0.0,'15/L.37/g  ','2010-04-19','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'VETER SHOP                                 ', '        ',NULL        ,7 ,'Via Lago Patria 184                                       ','Giugliano                              ','NA',0.0,0.0,'           ',NULL        ,'          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Tarantino Paolo e Co. Medicinali snc       ', '        ',NULL        ,8 ,'                                                          ','Frattamaggiore                         ','NA',0.0,0.0,'15/T.5/g   ','1993-05-14','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Cemon srl                                  ', '        ',NULL        ,8 ,'Via E.fermi                                               ','Grumo Nevano                           ','NA',0.0,0.0,'           ',NULL        ,'          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Farvima                                    ', '        ',NULL        ,8 ,'                                                          ','                                       ','NA',0.0,0.0,'15/F.21/g  ','2006-05-05','          ',NULL        ,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Vital zoo                                  ', '        ',NULL        ,8 ,'Via P.M.Vergara 72                                        ','Frattamaggiore                         ','NA',0.0,0.0,'15.v/22/g  ','2006-06-01','15/V.10/v ','2006-06-08','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Comifar distributore SPA                   ', '        ',NULL        ,8 ,'Via Marconi                                               ','Casavatore                             ','NA',0.0,0.0,'15/A.4/g   ',NULL        ,'          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Guacci Spa                                 ', '        ',NULL        ,9 ,'CIS di Nola Is 8 n.8092/95                                ','Nola                                   ','NA',0.0,0.0,'15/G.7/g   ','1993-03-24','15/G.7/v  ','1995-01-11','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'SO.FARMA.MORRA SPA                         ', '        ',NULL        ,9 ,'CIS di Nola Is 8 n.8092/95                                ','Nola                                   ','NA',0.0,0.0,'15/S.93/g  ','1999-02-9','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'SO.FARMA.MORRA SPA                         ', '        ',NULL        ,9 ,'CIS di Nola Is 8 n.8092/95                                ','Nola                                   ','NA',0.0,0.0,'15/S.7/g   ','2002-05-23','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Cofarmi farmacisti insieme spa             ', '        ',NULL        ,9 ,'interporto di nola zona asi lotto d1 blocco A1 civ 137/140','Nola                                   ','NA',0.0,0.0,'15/C.31/g  ','2007-05-04','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'La Veterinaria srl                         ', '        ',NULL        ,9 ,'Via Reg.Margherita 39                                     ','S.Anastasia                            ','NA',0.0,0.0,'15/L.28/g  ','1993-04-13','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Farmacampania Soc.Coop Arl                 ', '        ',NULL        ,9 ,'CIS di Nola Is 8 n.8036/8037                              ','Nola                                   ','NA',0.0,0.0,'F.15/F.20/g','2006-03-23','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'CE.DI.FAR. Srl                             ', '        ',NULL        ,9 ,'Via Nuova ponte delle Tavole                              ','S.Vitaliano                            ','NA',0.0,0.0,'15/C.27/g  ','1996-09-23','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'FARDEA Spa                                 ', '        ',NULL        ,9 ,'Via Naz. Delle Puglie Km 36,400                           ','Casalnuovo                             ','NA',0.0,0.0,'15/F.10/g  ','1993-05-07','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'SO.FARMA.MORRA SPA                         ', '        ',NULL        ,9 ,'CIS di Nola Is 1 n. 134                                   ','Nola                                   ','NA',0.0,0.0,'15/S.1/g   ','1993-10-05','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Dalvet srl                                 ', '        ',NULL        ,9 ,'Via S.M. del Pozzo 5/C                                    ','Somma vesuviana                        ','NA',0.0,0.0,'15/D.30/g  ','1995-04-07','15/D.30/v ','1995-05-15','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Nocefarm snc                               ', '        ',NULL        ,9 ,'Via Costantinopoli 142                                    ','Piazzolla di Nola                      ','NA',0.0,0.0,'15/N.21/g  ','1995-06-23','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Natella dr Carlo srl                       ', '        ',NULL        ,9 ,'Via Madonnelle 14                                         ','Castello di Cisterna Pomigliano d''arco','NA',0.0,0.0,'15/N.29/g  ','1994-02-22','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'S.I.V.A.S. Italia spa                      ', '        ',NULL        ,9 ,'Via trentola                                              ','Somma Vesuviana                        ','NA',0.0,0.0,'15/S.88/g  ','1998-01-19','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Laboratorio Vaccinogeno Paganini snc       ', '        ',NULL        ,10,'Via Diaz 147/149                                          ','Portici                                ','NA',0.0,0.0,'15/L.43/g  ','2000-10-09','15/L.43/V ','2000-10-17','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Centro Agroveta Campania                   ', '        ',NULL        ,11,'Via nazionale 188                                         ','Scafati Cortile di Palma               ','SA',0.0,0.0,'15/C.96/g  ','1993-01-04','15/C.96/v ','1993-07-23','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'De Pascale Annibale                        ', '        ',NULL        ,11,'Via della Liberta'' 78                                    ','Roccapiemonte                          ','SA',0.0,0.0,'15/D.32/g  ','1996-10-22','15/D.32/v ','1996-11-08','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Veterfarm srl                              ', 'revocato','2009-05-29',11,'Via trieste, 11                                           ','Castel san Giorgio                     ','SA',0.0,0.0,'15/V.27/g  ','1993-06-09','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Veterfarm srl                              ', 'revocato','2009-05-29',11,'Via trieste, 11                                           ','Castel san Giorgio                     ','SA',0.0,0.0,'           ','1999-02-02','15/V.27/v ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Veterinaria 2000                           ', '        ',NULL        ,12,'Parco Europa 92 SS 18                                     ','Contrada Pagliarone                    ','SA',0.0,0.0,'15/V.1/g   ','2001-11-15','15/V.1/V  ','2001-11-22','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'FARMAS srl                                 ', '        ',NULL        ,12,'Via Costanzella Calenda,2                                 ','Salerno                                ','SA',0.0,0.0,'15/F.3/g   ','2002-02-27','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'FARVINA Medicinali spa                     ', '        ',NULL        ,12,'Via Vesola Fuorni                                         ','Salerno                                ','SA',0.0,0.0,'15/F.21/g  ','1996-02-09','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Galenitalia spa                            ', '        ',NULL        ,12,'Via Zona della Porta 7                                    ','Salerno                                ','SA',0.0,0.0,'15/G.35/g  ','1999-07-15','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'V.I.M srl                                  ', '        ',NULL        ,12,'Via Costanzella Calenda,2                                 ','Salerno                                ','SA',0.0,0.0,'15/V.6/g   ','2002-05-08','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'PUMA FARM srl                              ', '        ',NULL        ,12,'Via S.Leonardo 120                                        ','Salerno                                ','SA',0.0,0.0,'15/P.8/g   ','2002-06-19','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Medivet                                    ', '        ',NULL        ,12,'Via M.Alfani 80                                           ','Pontecagnano-Faiano                    ','SA',0.0,0.0,'15/M.5/g   ','1993-04-29','15/M.5/v  ','1994-10-29','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Novafarma srl                              ', '        ',NULL        ,12,'                                                          ','Salerno                                ','SA',0.0,0.0,'15/N.1/g   ','1994-11-21','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Neofarma spa                               ', '        ',NULL        ,12,'Via della Porta                                           ','Salerno                                ','SA',0.0,0.0,'15/N.38/g  ','1996-10-07','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), '3 D Disinfettanti srl                      ', '        ',NULL        ,12,'Via Wenner 20/a                                           ','Salerno                                ','SA',0.0,0.0,'15/T.14/g  ','1994-11-29','15/T.14/v ','1995-02-13','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Zoofarmas snc                              ', '        ',NULL        ,12,'Via Acquasanta Z.I.                                       ','Salerno                                ','SA',0.0,0.0,'15/Z 9/g   ','1993-07-13','          ',NULL,'2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Medivet                                    ', '        ',NULL        ,12,'Via Alfani 80                                             ','Pontecagnano                           ','SA',0.0,0.0,'           ',NULL       ,'15/Z.9/v  ','1994-01-04','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Marvet                                     ', '        ',NULL        ,12,'Via Ponte Barizzo                                         ','Capaccio Scalo                         ','SA',0.0,0.0,'15/M.13/g  ','2003-04-03','15/M.13/V ','2005-09-20','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Zoomedical del Dr.Cobellis De Feo e C.     ', '        ',NULL        ,13,'Contr. Malagenia Z.I.                                     ','Ogliastro Cilento                      ','SA',0.0,0.0,'15/Z.26/g  ','1996-12-02','15/Z.26/V ','1996-12-09','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);
INSERT INTO farmacie (id_farmacia, ragione_sociale, stato,data_cambio_stato,site_id, indirizzo, citta,provincia, latitude, longitude, num_ric_ingrosso, data_ric_ingrosso, num_ric_dettaglio, data_ric_dettaglio,entered, enteredby, modified, modifiedby, trashed_date,id_prescrizione,pregresso, note1, data_verifica_annua) VALUES (nextval(('farmacia_id_seq')), 'Zoomedica Cilentana sas                    ', '        ',NULL        ,13,'Via Rettifilo 11713                                       ','Capaccio                               ','SA',0.0,0.0,'15/Z.57/g  ','1998-03-27','15/Z.57/V ','1998-04-20','2010-10-31',291,'2010-10-31',291,NULL,-1,true,NULL,NULL);

-- Completed on 2010-11-11 10:17:59

--
-- PostgreSQL database dump complete
--

