
package it.izs.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "controlliallevamenti", targetNamespace = "http://ws.izs.it")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Controlliallevamenti {


    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.UpdateControllistalledisostaResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "updateControllistalledisostaResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/updateControllistalledisostaRequest", output = "http://ws.izs.it/controlliallevamenti/updateControllistalledisostaResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControllistalledisosta/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControllistalledisosta/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControllistalledisosta/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControllistalledisosta/Fault/Exception")
    })
    public UpdateControllistalledisostaResponse updateControllistalledisosta(
        @WebParam(name = "updateControllistalledisosta", targetNamespace = "http://ws.izs.it", partName = "parameters")
        UpdateControllistalledisosta parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControllistalledisostaByPKResponse
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchControllistalledisostaByPKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControllistalledisostaByPKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControllistalledisostaByPKResponse", fault = {
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControllistalledisostaByPK/Fault/IzsWsException")
    })
    public SearchControllistalledisostaByPKResponse searchControllistalledisostaByPK(
        @WebParam(name = "searchControllistalledisostaByPK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControllistalledisostaByPK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws IzsWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControllistalledisostaByUKResponse
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchControllistalledisostaByUKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControllistalledisostaByUKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControllistalledisostaByUKResponse", fault = {
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControllistalledisostaByUK/Fault/IzsWsException")
    })
    public SearchControllistalledisostaByUKResponse searchControllistalledisostaByUK(
        @WebParam(name = "searchControllistalledisostaByUK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControllistalledisostaByUK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws IzsWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.InsertControllistalledisostaResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "insertControllistalledisostaResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/insertControllistalledisostaRequest", output = "http://ws.izs.it/controlliallevamenti/insertControllistalledisostaResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControllistalledisosta/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControllistalledisosta/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControllistalledisosta/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControllistalledisosta/Fault/Exception")
    })
    public InsertControllistalledisostaResponse insertControllistalledisosta(
        @WebParam(name = "insertControllistalledisosta", targetNamespace = "http://ws.izs.it", partName = "parameters")
        InsertControllistalledisosta parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.DeleteControllistalledisostaResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "deleteControllistalledisostaResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/deleteControllistalledisostaRequest", output = "http://ws.izs.it/controlliallevamenti/deleteControllistalledisostaResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControllistalledisosta/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControllistalledisosta/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControllistalledisosta/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControllistalledisosta/Fault/Exception")
    })
    public DeleteControllistalledisostaResponse deleteControllistalledisosta(
        @WebParam(name = "deleteControllistalledisosta", targetNamespace = "http://ws.izs.it", partName = "parameters")
        DeleteControllistalledisosta parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.InsertControlliallevamentiSAResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "insertControlliallevamentiSAResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSARequest", output = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSAResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSA/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSA/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSA/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSA/Fault/Exception")
    })
    public InsertControlliallevamentiSAResponse insertControlliallevamentiSA(
        @WebParam(name = "insertControlliallevamentiSA", targetNamespace = "http://ws.izs.it", partName = "parameters")
        InsertControlliallevamentiSA parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.UpdateControlliallevamentiSAResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "updateControlliallevamentiSAResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSARequest", output = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSAResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSA/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSA/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSA/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSA/Fault/Exception")
    })
    public UpdateControlliallevamentiSAResponse updateControlliallevamentiSA(
        @WebParam(name = "updateControlliallevamentiSA", targetNamespace = "http://ws.izs.it", partName = "parameters")
        UpdateControlliallevamentiSA parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.DeleteControlliallevamentiSAResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "deleteControlliallevamentiSAResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSARequest", output = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSAResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSA/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSA/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSA/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSA/Fault/Exception")
    })
    public DeleteControlliallevamentiSAResponse deleteControlliallevamentiSA(
        @WebParam(name = "deleteControlliallevamentiSA", targetNamespace = "http://ws.izs.it", partName = "parameters")
        DeleteControlliallevamentiSA parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControlliallevamentiSAByUKResponse
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchControlliallevamentiSAByUKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSAByUKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSAByUKResponse", fault = {
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSAByUK/Fault/IzsWsException")
    })
    public SearchControlliallevamentiSAByUKResponse searchControlliallevamentiSAByUK(
        @WebParam(name = "searchControlliallevamentiSAByUK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControlliallevamentiSAByUK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws IzsWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.InvioDocumentoResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "invioDocumentoResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/invioDocumentoRequest", output = "http://ws.izs.it/controlliallevamenti/invioDocumentoResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/invioDocumento/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/invioDocumento/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/invioDocumento/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/invioDocumento/Fault/Exception")
    })
    public InvioDocumentoResponse invioDocumento(
        @WebParam(name = "invioDocumento", targetNamespace = "http://ws.izs.it", partName = "parameters")
        InvioDocumento parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.AggiornamentoDocumentoResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "aggiornamentoDocumentoResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/aggiornamentoDocumentoRequest", output = "http://ws.izs.it/controlliallevamenti/aggiornamentoDocumentoResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/aggiornamentoDocumento/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/aggiornamentoDocumento/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/aggiornamentoDocumento/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/aggiornamentoDocumento/Fault/Exception")
    })
    public AggiornamentoDocumentoResponse aggiornamentoDocumento(
        @WebParam(name = "aggiornamentoDocumento", targetNamespace = "http://ws.izs.it", partName = "parameters")
        AggiornamentoDocumento parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.RicezioneDocumentoResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "ricezioneDocumentoResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/ricezioneDocumentoRequest", output = "http://ws.izs.it/controlliallevamenti/ricezioneDocumentoResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/ricezioneDocumento/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/ricezioneDocumento/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/ricezioneDocumento/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/ricezioneDocumento/Fault/Exception")
    })
    public RicezioneDocumentoResponse ricezioneDocumento(
        @WebParam(name = "ricezioneDocumento", targetNamespace = "http://ws.izs.it", partName = "parameters")
        RicezioneDocumento parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.CancellazioneDocumentoResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "cancellazioneDocumentoResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/cancellazioneDocumentoRequest", output = "http://ws.izs.it/controlliallevamenti/cancellazioneDocumentoResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/cancellazioneDocumento/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/cancellazioneDocumento/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/cancellazioneDocumento/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/cancellazioneDocumento/Fault/Exception")
    })
    public CancellazioneDocumentoResponse cancellazioneDocumento(
        @WebParam(name = "cancellazioneDocumento", targetNamespace = "http://ws.izs.it", partName = "parameters")
        CancellazioneDocumento parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.InsertControlliallevamentiResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "insertControlliallevamentiResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiRequest", output = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamenti/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamenti/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamenti/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamenti/Fault/Exception")
    })
    public InsertControlliallevamentiResponse insertControlliallevamenti(
        @WebParam(name = "insertControlliallevamenti", targetNamespace = "http://ws.izs.it", partName = "parameters")
        InsertControlliallevamenti parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.InsertControlliallevamentiBAResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "insertControlliallevamentiBAResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiBARequest", output = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiBAResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiBA/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiBA/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiBA/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiBA/Fault/Exception")
    })
    public InsertControlliallevamentiBAResponse insertControlliallevamentiBA(
        @WebParam(name = "insertControlliallevamentiBA", targetNamespace = "http://ws.izs.it", partName = "parameters")
        InsertControlliallevamentiBA parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.UpdateControlliallevamentiBAResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "updateControlliallevamentiBAResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiBARequest", output = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiBAResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiBA/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiBA/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiBA/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiBA/Fault/Exception")
    })
    public UpdateControlliallevamentiBAResponse updateControlliallevamentiBA(
        @WebParam(name = "updateControlliallevamentiBA", targetNamespace = "http://ws.izs.it", partName = "parameters")
        UpdateControlliallevamentiBA parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.DeleteControlliallevamentiBAResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "deleteControlliallevamentiBAResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiBARequest", output = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiBAResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiBA/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiBA/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiBA/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiBA/Fault/Exception")
    })
    public DeleteControlliallevamentiBAResponse deleteControlliallevamentiBA(
        @WebParam(name = "deleteControlliallevamentiBA", targetNamespace = "http://ws.izs.it", partName = "parameters")
        DeleteControlliallevamentiBA parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControlliallevamentiBAByPKResponse
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchControlliallevamentiBAByPKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiBAByPKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiBAByPKResponse", fault = {
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiBAByPK/Fault/IzsWsException")
    })
    public SearchControlliallevamentiBAByPKResponse searchControlliallevamentiBAByPK(
        @WebParam(name = "searchControlliallevamentiBAByPK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControlliallevamentiBAByPK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws IzsWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControlliallevamentiBAByUKResponse
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchControlliallevamentiBAByUKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiBAByUKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiBAByUKResponse", fault = {
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiBAByUK/Fault/IzsWsException")
    })
    public SearchControlliallevamentiBAByUKResponse searchControlliallevamentiBAByUK(
        @WebParam(name = "searchControlliallevamentiBAByUK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControlliallevamentiBAByUK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws IzsWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.UpdateEsitoResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "updateEsitoResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/updateEsitoRequest", output = "http://ws.izs.it/controlliallevamenti/updateEsitoResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateEsito/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateEsito/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateEsito/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateEsito/Fault/Exception")
    })
    public UpdateEsitoResponse updateEsito(
        @WebParam(name = "updateEsito", targetNamespace = "http://ws.izs.it", partName = "parameters")
        UpdateEsito parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.UpdateControlliallevamentiResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "updateControlliallevamentiResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiRequest", output = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamenti/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamenti/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamenti/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamenti/Fault/Exception")
    })
    public UpdateControlliallevamentiResponse updateControlliallevamenti(
        @WebParam(name = "updateControlliallevamenti", targetNamespace = "http://ws.izs.it", partName = "parameters")
        UpdateControlliallevamenti parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.DeleteControlliallevamentiResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteControlliallevamentiResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiRequest", output = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamenti/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamenti/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamenti/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamenti/Fault/Exception")
    })
    public DeleteControlliallevamentiResponse deleteControlliallevamenti(
        @WebParam(name = "deleteControlliallevamenti", targetNamespace = "http://ws.izs.it", partName = "parameters")
        DeleteControlliallevamenti parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControlliallevamentiByPKResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "searchControlliallevamentiByPKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByPKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByPKResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByPK/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByPK/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByPK/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByPK/Fault/Exception")
    })
    public SearchControlliallevamentiByPKResponse searchControlliallevamentiByPK(
        @WebParam(name = "searchControlliallevamentiByPK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControlliallevamentiByPK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControlliallevamentiByUKResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws SOAPException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "searchControlliallevamentiByUKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByUKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByUKResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByUK/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByUK/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByUK/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiByUK/Fault/Exception")
    })
    public SearchControlliallevamentiByUKResponse searchControlliallevamentiByUK(
        @WebParam(name = "searchControlliallevamentiByUK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControlliallevamentiByUK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.InsertControlliallevamentiSVResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "insertControlliallevamentiSVResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSVRequest", output = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSVResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSV/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSV/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSV/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/insertControlliallevamentiSV/Fault/Exception")
    })
    public InsertControlliallevamentiSVResponse insertControlliallevamentiSV(
        @WebParam(name = "insertControlliallevamentiSV", targetNamespace = "http://ws.izs.it", partName = "parameters")
        InsertControlliallevamentiSV parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.UpdateControlliallevamentiSVResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "updateControlliallevamentiSVResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSVRequest", output = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSVResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSV/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSV/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSV/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/updateControlliallevamentiSV/Fault/Exception")
    })
    public UpdateControlliallevamentiSVResponse updateControlliallevamentiSV(
        @WebParam(name = "updateControlliallevamentiSV", targetNamespace = "http://ws.izs.it", partName = "parameters")
        UpdateControlliallevamentiSV parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.DeleteControlliallevamentiSVResponse
     * @throws IzsWsException_Exception
     * @throws BusinessException_Exception
     * @throws Exception_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteControlliallevamentiSVResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSVRequest", output = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSVResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSV/Fault/SOAPException"),
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSV/Fault/IzsWsException"),
        @FaultAction(className = BusinessException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSV/Fault/BusinessException"),
        @FaultAction(className = Exception_Exception.class, value = "http://ws.izs.it/controlliallevamenti/deleteControlliallevamentiSV/Fault/Exception")
    })
    public DeleteControlliallevamentiSVResponse deleteControlliallevamentiSV(
        @WebParam(name = "deleteControlliallevamentiSV", targetNamespace = "http://ws.izs.it", partName = "parameters")
        DeleteControlliallevamentiSV parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws BusinessException_Exception, Exception_Exception, IzsWsException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControlliallevamentiSVByPKResponse
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchControlliallevamentiSVByPKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSVByPKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSVByPKResponse", fault = {
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSVByPK/Fault/IzsWsException")
    })
    public SearchControlliallevamentiSVByPKResponse searchControlliallevamentiSVByPK(
        @WebParam(name = "searchControlliallevamentiSVByPK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControlliallevamentiSVByPK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws IzsWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControlliallevamentiSVByUKResponse
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchControlliallevamentiSVByUKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSVByUKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSVByUKResponse", fault = {
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSVByUK/Fault/IzsWsException")
    })
    public SearchControlliallevamentiSVByUKResponse searchControlliallevamentiSVByUK(
        @WebParam(name = "searchControlliallevamentiSVByUK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControlliallevamentiSVByUK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws IzsWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazione
     * @param parameters
     * @param soapAutorizzazione
     * @return
     *     returns it.izs.ws.SearchControlliallevamentiSAByPKResponse
     * @throws IzsWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchControlliallevamentiSAByPKResponse", targetNamespace = "http://ws.izs.it", partName = "result")
    @Action(input = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSAByPKRequest", output = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSAByPKResponse", fault = {
        @FaultAction(className = IzsWsException_Exception.class, value = "http://ws.izs.it/controlliallevamenti/searchControlliallevamentiSAByPK/Fault/IzsWsException")
    })
    public SearchControlliallevamentiSAByPKResponse searchControlliallevamentiSAByPK(
        @WebParam(name = "searchControlliallevamentiSAByPK", targetNamespace = "http://ws.izs.it", partName = "parameters")
        SearchControlliallevamentiSAByPK parameters,
        @WebParam(name = "SOAPAutenticazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutenticazione")
        AutenticazioneTO soapAutenticazione,
        @WebParam(name = "SOAPAutorizzazione", targetNamespace = "http://ws.izs.it", header = true, partName = "SOAPAutorizzazione")
        AutorizzazioneTO soapAutorizzazione)
        throws IzsWsException_Exception
    ;

}
