
package it.izs.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IzsWsException", targetNamespace = "http://ws.izs.it")
public class IzsWsException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IzsWsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IzsWsException_Exception(String message, IzsWsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IzsWsException_Exception(String message, IzsWsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.izs.ws.IzsWsException
     */
    public IzsWsException getFaultInfo() {
        return faultInfo;
    }

}
