
package it.izs.apicoltura.apianagraficaattivita.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApiattEndpoint", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApiattEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.InsertApiAttivitaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertApiAttivitaResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/insertApiAttivitaRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/insertApiAttivitaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/insertApiAttivita/Fault/BusinessWsException")
    })
    public InsertApiAttivitaResponse insertApiAttivita(
        @WebParam(name = "insertApiAttivita", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        InsertApiAttivita parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.UpdateApiAttivitaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateApiAttivitaResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/updateApiAttivitaRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/updateApiAttivitaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/updateApiAttivita/Fault/BusinessWsException")
    })
    public UpdateApiAttivitaResponse updateApiAttivita(
        @WebParam(name = "updateApiAttivita", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        UpdateApiAttivita parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.DeleteApiAttivitaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteApiAttivitaResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/deleteApiAttivitaRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/deleteApiAttivitaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/deleteApiAttivita/Fault/BusinessWsException")
    })
    public DeleteApiAttivitaResponse deleteApiAttivita(
        @WebParam(name = "deleteApiAttivita", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        DeleteApiAttivita parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchApiAttivitaResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchApiAttivitaResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/searchApiAttivitaRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/searchApiAttivitaResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/searchApiAttivita/Fault/BusinessWsException")
    })
    public SearchApiAttivitaResponse searchApiAttivita(
        @WebParam(name = "searchApiAttivita", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiAttivita parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchApiAttivitaByPkResponse
     */
    @WebMethod
    @WebResult(name = "searchApiAttivitaByPkResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/searchApiAttivitaByPkRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiattEndpoint/searchApiAttivitaByPkResponse")
    public SearchApiAttivitaByPkResponse searchApiAttivitaByPk(
        @WebParam(name = "searchApiAttivitaByPk", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiAttivitaByPk parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

}
