
package it.izs.apicoltura.apianagraficaattivita.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.aspcfs.modules.util.imports.ApplicationProperties;
import org.json.JSONObject;

import configurazione.centralizzata.nuova.gestione.ClientServizioCentralizzato;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */


@WebServiceClient(name = "ApiattEndpointService", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", wsdlLocation = ConfiguratoreServizi.END_POINT+ "ws/apicoltura/apianagrafica/apiattivita?wsdl")
public class ApiattEndpointService
    extends Service	
{
		
    private final static URL APIATTENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException APIATTENDPOINTSERVICE_EXCEPTION;
    private final static QName APIATTENDPOINTSERVICE_QNAME = new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiattEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	if(ApplicationProperties.getProperty("recupero_wsdl_locale").equals("true"))
        	{
        		ClientServizioCentralizzato sclient = new ClientServizioCentralizzato();
        		JSONObject mappaEndPoints = sclient.getMappaEndpointsSca();
        		String urlGisa = null;
				if(mappaEndPoints.has("gisa_lan")){
					urlGisa = mappaEndPoints.getString("gisa_lan");

				}
					if(urlGisa==null || urlGisa.equals(""))
        			urlGisa = mappaEndPoints.getString("gisa");
				
        		url = new URL(urlGisa + "/" + ApplicationProperties.getProperty("END_POINT_BDAPI_LOCALE_ATTIVITA"));
        	}
        	else
        		url =  new URL(ApplicationProperties.getProperty("END_POINT_BDAPI")+ "ws/apicoltura/apianagrafica/apiattivita?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        APIATTENDPOINTSERVICE_WSDL_LOCATION = url;
        APIATTENDPOINTSERVICE_EXCEPTION = e;
    }

    public ApiattEndpointService() {
        super(__getWsdlLocation(), APIATTENDPOINTSERVICE_QNAME);
    }

    public ApiattEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APIATTENDPOINTSERVICE_QNAME, features);
    }

    public ApiattEndpointService(URL wsdlLocation) {
        super(wsdlLocation, APIATTENDPOINTSERVICE_QNAME);
    }

    public ApiattEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APIATTENDPOINTSERVICE_QNAME, features);
    }

    public ApiattEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiattEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApiattEndpoint
     */
    @WebEndpoint(name = "ApiattEndpointPort")
    public ApiattEndpoint getApiattEndpointPort() {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiattEndpointPort"), ApiattEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiattEndpoint
     */
    @WebEndpoint(name = "ApiattEndpointPort")
    public ApiattEndpoint getApiattEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiattEndpointPort"), ApiattEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APIATTENDPOINTSERVICE_EXCEPTION!= null) {
            throw APIATTENDPOINTSERVICE_EXCEPTION;
        }
        
        System.out.println("##API WSDL LOCATION -->"+APIATTENDPOINTSERVICE_WSDL_LOCATION);
        return APIATTENDPOINTSERVICE_WSDL_LOCATION;
    }

}
