
package it.izs.apicoltura.apianagraficaattivita.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
 

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApicenEndpoint", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApicenEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchApiCensimentoResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchApiCensimentoResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/searchApiCensimentoRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/searchApiCensimentoResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/searchApiCensimento/Fault/BusinessWsException")
    })
    public SearchApiCensimentoResponse searchApiCensimento(
        @WebParam(name = "searchApiCensimento", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiCensimento parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchApiCensimentoByPkResponse
     */
    @WebMethod
    @WebResult(name = "searchApiCensimentoByPkResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/searchApiCensimentoByPkRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/searchApiCensimentoByPkResponse")
    public SearchApiCensimentoByPkResponse searchApiCensimentoByPk(
        @WebParam(name = "searchApiCensimentoByPk", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiCensimentoByPk parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.InsertApiCensimentoResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertApiCensimentoResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/insertApiCensimentoRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/insertApiCensimentoResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/insertApiCensimento/Fault/BusinessWsException")
    })
    public InsertApiCensimentoResponse insertApiCensimento(
        @WebParam(name = "insertApiCensimento", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        InsertApiCensimento parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.UpdateApiCensimentoResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateApiCensimentoResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/updateApiCensimentoRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/updateApiCensimentoResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/updateApiCensimento/Fault/BusinessWsException")
    })
    public UpdateApiCensimentoResponse updateApiCensimento(
        @WebParam(name = "updateApiCensimento", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        UpdateApiCensimento parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.DeleteApiCensimentoResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteApiCensimentoResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/deleteApiCensimentoRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/deleteApiCensimentoResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApicenEndpoint/deleteApiCensimento/Fault/BusinessWsException")
    })
    public DeleteApiCensimentoResponse deleteApiCensimento(
        @WebParam(name = "deleteApiCensimento", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        DeleteApiCensimento parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

}
