
package it.izs.apicoltura.apianagraficaattivita.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.aspcfs.modules.util.imports.ApplicationProperties;
import org.json.JSONObject;

import configurazione.centralizzata.nuova.gestione.ClientServizioCentralizzato;
 

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApicenEndpointService", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", wsdlLocation = ConfiguratoreServizi.END_POINT+"ws/apicoltura/apianagrafica/apicensimento?wsdl")
public class ApicenEndpointService
    extends Service
{

    private final static URL APICENENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException APICENENDPOINTSERVICE_EXCEPTION;
    private final static QName APICENENDPOINTSERVICE_QNAME = new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApicenEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	if(ApplicationProperties.getProperty("recupero_wsdl_locale").equals("true"))
        	{
        		ClientServizioCentralizzato sclient = new ClientServizioCentralizzato();
        		JSONObject mappaEndPoints = sclient.getMappaEndpointsSca();
        		
        		
        		String urlGisa = null;
				if(mappaEndPoints.has("gisa_lan")){
					urlGisa = mappaEndPoints.getString("gisa_lan");

				}
					if(urlGisa==null || urlGisa.equals(""))
        			urlGisa = mappaEndPoints.getString("gisa");
				
        		url = new URL(urlGisa + "/" + ApplicationProperties.getProperty("END_POINT_BDAPI_LOCALE_CENSIMENTI"));
        	}
        	else
        		url =   new URL(ApplicationProperties.getProperty("END_POINT_BDAPI")+"ws/apicoltura/apianagrafica/apicensimento?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        APICENENDPOINTSERVICE_WSDL_LOCATION = url;
        APICENENDPOINTSERVICE_EXCEPTION = e;
    }

    public ApicenEndpointService() {
        super(__getWsdlLocation(), APICENENDPOINTSERVICE_QNAME);
    }

    public ApicenEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APICENENDPOINTSERVICE_QNAME, features);
    }

    public ApicenEndpointService(URL wsdlLocation) {
        super(wsdlLocation, APICENENDPOINTSERVICE_QNAME);
    }

    public ApicenEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APICENENDPOINTSERVICE_QNAME, features);
    }

    public ApicenEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApicenEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApicenEndpoint
     */
    @WebEndpoint(name = "ApicenEndpointPort")
    public ApicenEndpoint getApicenEndpointPort() {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApicenEndpointPort"), ApicenEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApicenEndpoint
     */
    @WebEndpoint(name = "ApicenEndpointPort")
    public ApicenEndpoint getApicenEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApicenEndpointPort"), ApicenEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APICENENDPOINTSERVICE_EXCEPTION!= null) {
            throw APICENENDPOINTSERVICE_EXCEPTION;
        }
        System.out.println("##API WSDL LOCATION -->"+APICENENDPOINTSERVICE_WSDL_LOCATION);
        return APICENENDPOINTSERVICE_WSDL_LOCATION;
    }

}
