
package it.izs.apicoltura.apianagraficaattivita.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.aspcfs.modules.util.imports.ApplicationProperties;
import org.json.JSONObject;

import configurazione.centralizzata.nuova.gestione.ClientServizioCentralizzato;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */





@WebServiceClient(name = "ApiEndpointService", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", wsdlLocation = ConfiguratoreServizi.END_POINT +"ws/apicoltura/apianagrafica/apiario?wsdl")
public class ApiEndpointService
    extends Service
{
	
    private final static URL APIENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException APIENDPOINTSERVICE_EXCEPTION;
    private final static QName APIENDPOINTSERVICE_QNAME = new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	if(ApplicationProperties.getProperty("recupero_wsdl_locale").equals("true"))
        	{
        		ClientServizioCentralizzato sclient = new ClientServizioCentralizzato();
        		JSONObject mappaEndPoints = sclient.getMappaEndpointsSca();
        		String urlGisa = null;
				if(mappaEndPoints.has("gisa_lan")){
					urlGisa = mappaEndPoints.getString("gisa_lan");

				}
					if(urlGisa==null || urlGisa.equals(""))
        			urlGisa = mappaEndPoints.getString("gisa");
				
        		url = new URL(urlGisa + "/" + ApplicationProperties.getProperty("END_POINT_BDAPI_LOCALE_API"));
        	}
        	else
        		url =  new URL(ApplicationProperties.getProperty("END_POINT_BDAPI")+"ws/apicoltura/apianagrafica/apiario?wsdl");
        	
        	
        	System.out.println("### API-URL WEB SERVICE -->"+ url);
        	
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        APIENDPOINTSERVICE_WSDL_LOCATION = url;
        APIENDPOINTSERVICE_EXCEPTION = e;
    }

    public ApiEndpointService() {
        super(__getWsdlLocation(), APIENDPOINTSERVICE_QNAME);
    }

    public ApiEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APIENDPOINTSERVICE_QNAME, features);
    }

    public ApiEndpointService(URL wsdlLocation) {
        super(wsdlLocation, APIENDPOINTSERVICE_QNAME);
    }

    public ApiEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APIENDPOINTSERVICE_QNAME, features);
    }

    public ApiEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApiEndpoint
     */
    @WebEndpoint(name = "ApiEndpointPort")
    public ApiEndpoint getApiEndpointPort() {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiEndpointPort"), ApiEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiEndpoint
     */
    @WebEndpoint(name = "ApiEndpointPort")
    public ApiEndpoint getApiEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApiEndpointPort"), ApiEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APIENDPOINTSERVICE_EXCEPTION!= null) {
            throw APIENDPOINTSERVICE_EXCEPTION;
        }
        System.out.println("##API WSDL LOCATION -->"+APIENDPOINTSERVICE_WSDL_LOCATION);
        return APIENDPOINTSERVICE_WSDL_LOCATION;
    }

}
