
package it.izs.apicoltura.apianagraficaattivita.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.aspcfs.modules.util.imports.ApplicationProperties;
import org.json.JSONObject;

import configurazione.centralizzata.nuova.gestione.ClientServizioCentralizzato;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApistodetEndpointService", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", wsdlLocation = ConfiguratoreServizi.END_POINT+"ws/apicoltura/apianagrafica/storicodetentore?wsdl")
public class ApistodetEndpointService
    extends Service
{

    private final static URL APISTODETENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException APISTODETENDPOINTSERVICE_EXCEPTION;
    private final static QName APISTODETENDPOINTSERVICE_QNAME = new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApistodetEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	if(ApplicationProperties.getProperty("recupero_wsdl_locale").equals("true"))
        	{
        		ClientServizioCentralizzato sclient = new ClientServizioCentralizzato();
        		JSONObject mappaEndPoints = sclient.getMappaEndpointsSca();
        		String urlGisa = null;
				if(mappaEndPoints.has("gisa_lan")){
					urlGisa = mappaEndPoints.getString("gisa_lan");

				}
					if(urlGisa==null || urlGisa.equals(""))
        			urlGisa = mappaEndPoints.getString("gisa");
				
        		url = new URL(urlGisa + "/" + ApplicationProperties.getProperty("END_POINT_BDAPI_LOCALE_STORICODETENTORE"));
        	}
        	else
        		url =  new URL(ApplicationProperties.getProperty("END_POINT_BDAPI")+"ws/apicoltura/apianagrafica/storicodetentore?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        APISTODETENDPOINTSERVICE_WSDL_LOCATION = url;
        APISTODETENDPOINTSERVICE_EXCEPTION = e;
    }

    public ApistodetEndpointService() {
        super(__getWsdlLocation(), APISTODETENDPOINTSERVICE_QNAME);
    }

    public ApistodetEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APISTODETENDPOINTSERVICE_QNAME, features);
    }

    public ApistodetEndpointService(URL wsdlLocation) {
        super(wsdlLocation, APISTODETENDPOINTSERVICE_QNAME);
    }

    public ApistodetEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APISTODETENDPOINTSERVICE_QNAME, features);
    }

    public ApistodetEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApistodetEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApistodetEndpoint
     */
    @WebEndpoint(name = "ApistodetEndpointPort")
    public ApistodetEndpoint getApistodetEndpointPort() {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApistodetEndpointPort"), ApistodetEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApistodetEndpoint
     */
    @WebEndpoint(name = "ApistodetEndpointPort")
    public ApistodetEndpoint getApistodetEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.apianagrafica.apicoltura.izs.it/", "ApistodetEndpointPort"), ApistodetEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APISTODETENDPOINTSERVICE_EXCEPTION!= null) {
            throw APISTODETENDPOINTSERVICE_EXCEPTION;
        }
        System.out.println("##API WSDL LOCATION -->"+APISTODETENDPOINTSERVICE_WSDL_LOCATION);
        return APISTODETENDPOINTSERVICE_WSDL_LOCATION;
    }

}
