
package it.izs.apicoltura.apianagraficaattivita.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApiubiEndpoint", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApiubiEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.UpdateApiUbicazioneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateApiUbicazioneResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/updateApiUbicazioneRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/updateApiUbicazioneResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/updateApiUbicazione/Fault/BusinessWsException")
    })
    public UpdateApiUbicazioneResponse updateApiUbicazione(
        @WebParam(name = "updateApiUbicazione", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        UpdateApiUbicazione parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.DeleteApiUbicazioneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteApiUbicazioneResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/deleteApiUbicazioneRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/deleteApiUbicazioneResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/deleteApiUbicazione/Fault/BusinessWsException")
    })
    public DeleteApiUbicazioneResponse deleteApiUbicazione(
        @WebParam(name = "deleteApiUbicazione", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        DeleteApiUbicazione parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchApiUbicazioneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchApiUbicazioneResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/searchApiUbicazioneRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/searchApiUbicazioneResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/searchApiUbicazione/Fault/BusinessWsException")
    })
    public SearchApiUbicazioneResponse searchApiUbicazione(
        @WebParam(name = "searchApiUbicazione", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiUbicazione parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchApiUbicazioneByPkResponse
     */
    @WebMethod
    @WebResult(name = "searchApiUbicazioneByPkResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/searchApiUbicazioneByPkRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/searchApiUbicazioneByPkResponse")
    public SearchApiUbicazioneByPkResponse searchApiUbicazioneByPk(
        @WebParam(name = "searchApiUbicazioneByPk", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiUbicazioneByPk parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.InsertApiUbicazioneResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertApiUbicazioneResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/insertApiUbicazioneRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/insertApiUbicazioneResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiubiEndpoint/insertApiUbicazione/Fault/BusinessWsException")
    })
    public InsertApiUbicazioneResponse insertApiUbicazione(
        @WebParam(name = "insertApiUbicazione", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        InsertApiUbicazione parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

}
