-- CHI: Bartolo Sansone	
-- COSA: Scheda centralizzata haccp
-- QUANDO: 10/01/2018

insert into lookup_tipo_scheda_operatore(code, description, level, enabled, titolo, firma_data, nome_file) values (40, 'Laboratori HACCP', 0, true, 'Scheda Operatore', false, 'SchedaOperatore');

update scheda_operatore_metadati set enabled = false where tipo_operatore = 40;insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','INFORMAZIONE PRIMARIA','capitolo','','','','a','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','ASL ','asl','asl.description as descr_asl ','lookup_site_id asl left join organization o on o.site_id = asl.code ','o.org_id = #orgid#','b','print');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','ASL','','asl.description as descr_asl ','lookup_site_id asl left join organization o on o.site_id = asl.code ','o.org_id = #orgid#','c','screen');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','DENOMINAZIONE','','name as ragione_sociale ','organization ','org_id = #orgid#','d','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','NUMERO DI ISCRIZIONE','barcode','account_number as numero_registrazione ','organization ','org_id = #orgid#','e','print');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','PARTITA IVA','','partita_iva as partita_iva ','organization ','org_id = #orgid#','f','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','DIRETTORE RESPONSABILE LABORATORIO','','cognome_rappresentante','organization ','org_id = #orgid#','g','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','STATO STABILIMENTO','','case when stato is null or stato = '''' then ''ATTIVO'' else stato ||'' in data '' || to_char(data_cambio_stato, ''dd/MM/yy'')  end

','organization ','org_id = #orgid# ','h','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','SEDE LEGALE','capitolo','','','','i','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','INDIRIZZO SEDE LEGALE','','case when upper(oaleg.addrline1) is not null then upper(oaleg.addrline1) else  '' '' end || '',  ''|| case when upper(oaleg.city) is not null  then upper(oaleg.city) else  '' '' end || '',  ''|| case when oaleg.postalcode is not null  then oaleg.postalcode else  '' '' end || '', ''|| case when oaleg.state is not null  then oaleg.state else  '' '' end as ind_sede_operativa ','organization o left join organization_address oaleg on (o.org_id = oaleg.org_id and oaleg.address_type = 1) ','o.org_id = #orgid#','l','print');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','INDIRIZZO SEDE LEGALE ','indirizzo','case when upper(oaleg.addrline1) is not null then upper(oaleg.addrline1) else  '' '' end || '',  ''|| case when upper(oaleg.city) is not null  then upper(oaleg.city) else  '' '' end || '',  ''|| case when oaleg.postalcode is not null  then oaleg.postalcode else  '' '' end || '', ''|| case when oaleg.state is not null  then oaleg.state else  '' '' end','organization o left join organization_address oaleg on (o.org_id = oaleg.org_id and oaleg.address_type = 1) ','o.org_id = #orgid#','m','screen');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','SEDE OPERATIVA','capitolo','','','','n','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','INDIRIZZO SEDE OPERATIVA','','case when upper(oaope.addrline1) is not null then upper(oaope.addrline1) else  '' '' end || '',  ''|| case when upper(oaope.city) is not null  then upper(oaope.city) else  '' '' end || '',  ''|| case when oaope.postalcode is not null  then oaope.postalcode else  '' '' end || '', ''|| case when oaope.state is not null  then oaope.state else  '' '' end as ind_sede_operativa ','organization o left join organization_address oaope on (o.org_id = oaope.org_id and oaope.address_type = 5) ','o.org_id = #orgid#
','o','print');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','INDIRIZZO SEDE OPERATIVA ','indirizzo','case when upper(oaope.addrline1) is not null then upper(oaope.addrline1) else  '' '' end || '',  ''|| case when upper(oaope.city) is not null  then upper(oaope.city) else  '' '' end || '',  ''|| case when oaope.postalcode is not null  then oaope.postalcode else  '' '' end || '', ''|| case when oaope.state is not null  then oaope.state else  '' '' end','organization o left join organization_address oaope on (o.org_id = oaope.org_id and oaope.address_type = 5) ','o.org_id = #orgid#
','p','screen');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','LISTA LINEE PRODUTTIVE','capitolo','','','','q','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','ATTIVITA','','norma ||''<br/>''|| macroarea ||''<br/>''|| aggregazione ||''<br/>''||attivita','ricerche_anagrafiche_old_materializzata','riferimento_id = #orgid# and riferimento_id_nome_col = ''org_id''','r','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','ELENCO PROVE','capitolo','','','','S','');insert into scheda_operatore_metadati(tipo_operatore, label, attributo, sql_campo, sql_origine, sql_condizione, ordine, destinazione) values ('40','PROVE','','''<b>Materiale/Prodotto/Matrice: </b> ''|| matrici.description  
|| ''; <b>Denominazione prova </b> '' || denominazioni.description
|| ''; <b>Norma/Metodo: </b> '' || prove.norma
|| ''; <b>Accreditata/In accreditamento: </b> '' || case when prove.accreditata then ''ACCREDITATA'' else ''IN ACCREDITAMENTO'' end 
|| ''; <b>Ente Accreditamento: </b> '' || enti.description ','laboratorihaccp_elenco_prove prove
left join lookup_denominazioni_labhaccp denominazioni on denominazioni.code = prove.codice_denominazione
left join lookup_matrici_labhaccp matrici on matrici.code = prove.codice_matrice
left join lookup_ente_labhaccp enti on enti.code = prove.codice_ente','prove.org_id = #orgid# and prove.enabled and prove.trashed_date is null','T','');